### ISSUE TITLE
New iOS release (v.3) doesn't compile

### ISSUE THREAD

**Issue by PietroGranati** [hansemannn/titanium-firebase-cloud-messaging#101]
Hi, since I got some problems receiving notifications with the last ios update, I've tryed compile the module.
It compiles but when I put in the app and compile I got conflict errors:
`TRACE] :  duplicate symbol '_kFIRLoggerMessaging' in:
[TRACE] :      /Users/pietrogranati/Library/Application Support/Titanium/modules/iphone/firebase.core/2.2.0/platform/FirebaseCore.framework/FirebaseCore(FIRLogger.o)
[TRACE] :      /Users/pietrogranati/Library/Application Support/Titanium/modules/iphone/firebase.cloudmessaging/3.0.0/platform/FirebaseMessaging.framework/FirebaseMessaging(FIRMessagingLogger.o)
[TRACE] :  ld: 1 duplicate symbol for architecture armv7
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by Astrovic** [comment]
I am experiencing the same issue. Have you found any solution? With version 2.0.1 I receive notifications, but when I click on the notification, `notification` event is not triggered

**Comment by hansemannn** [comment]
Use Firebase-Core 3.0.0 and Firebase-Cloud-Messing 3.0.0
