### ISSUE TITLE
Problem getting Android icon Badge

### ISSUE THREAD

**Issue by Wingee** [hansemannn/titanium-firebase-cloud-messaging#106]
I'm using the v1 Firebase Cloud Messaging API rather than the Legacy HTTP method in the Readme Example.

But the Badge never shows on my Samsung S10 running Android 10 

Here is the payload going to FCM

`{
    "message": {
        "name": "1341854",
        "notification": {
            "title": "One of your jobs has been unassigned",
            "body": "Message"
        },
        "android": {
            "priority": "high",
            "notification": {
                "notification_count": 279,
                "tag": "default",
                "color": "#009DDB",
                "sound": "default",
                "channel_id": "default"
            }
        },
        "data": {
            "type": "PUSH_TYPE_MESSAGE",
            "channelId": "default",
            "id": "131854",
            "badge": "279"
        },
        "token": "sometoken"
    }
}`

I'm using version 2.0.4 of the module

**Comment by m1ga** [comment]
could you please try this version: http://migaweb.de/firebase.cloudmessaging-android-2.0.4.zip

**Comment by Wingee** [comment]
Thanks @m1ga but it's still not showing the badge number I've set. 
The number of notifications in the tray does show in the badge, but it doesn't show the value that is sent in the payload

**Comment by m1ga** [comment]
is the data part actually arriving in the app` So if you do
```
function onMessage(e) {
	alert("Got message: " + JSON.stringify(e.message.data));
}
```
will it show the data fields? I've just tried it on a Samsung A5 and it works fine. It will always set the number I've set inside my data - badge field

**Comment by Wingee** [comment]
@m1ga yes the data part is arriving in the app as I'm reading that data for other things.
I've got a Samsung A3 I can try. What version of Android does your A5 run?

**Comment by Wingee** [comment]
Same result on the A3 - no badge number. Other apps have badge numbers but mine doesn't )-:

**Comment by m1ga** [comment]
Can you please post the output of:
```
function onMessage(e) {
	console.log("Got message: " + JSON.stringify(e.message.data));
}
```
want to see if there is anything else that is blocking it

**Comment by Wingee** [comment]
Thanks @m1ga for your help. Here is the output:

`{"channelId":"default","type":"PUSH_TYPE_MESSAGE","id":"1339974494","badge":"148"}`

**Comment by m1ga** [comment]
Could you please add a `title` to the data block.

**Comment by Wingee** [comment]
I have tried this on the Samsung A3 and S10.

The data block is like this:

`{"publicId":"29UGER","channelId":"default","title":"Please Acknowledge","id":"15365491","badge":"148","type":"PUSH_TYPE_ACKNOWLEDGEMENT"}`

But no badge number is appearing. Any other ideas?

**Comment by m1ga** [comment]
try to run this in a terminal:
```
curl -i -H 'Content-type: application/json' -H 'Authorization: key=#####KEY#####' -XPOST https://fcm.googleapis.com/fcm/send -d '{
  "registration_ids":["####DEVICE_ID#####"],
  "data": {"publicId":"29UGER","channelId":"default","title":"Please Acknowledge","message":"","id":"15365492","badge":"150","type":"PUSH_TYPE_ACKNOWLEDGEMENT"}
}'
```
make sure to insert your key and device_id

**Comment by Wingee** [comment]
That works @m1ga but that's using the old method. Google are suggest migrating sending this way:

https://firebase.google.com/docs/cloud-messaging/migrate-v1

We've migrated over, but the badges are the one thing that doesn't work

**Comment by m1ga** [comment]
even then it works fine. Very complex and time consuming to setup:
```javascript
var {
	google
} = require('googleapis');
var MESSAGING_SCOPE = 'https://www.googleapis.com/auth/firebase.messaging';
var SCOPES = [MESSAGING_SCOPE];
const https = require('https');

function getAccessToken() {
	return new Promise(function(resolve, reject) {
		var key = require('./key.json');
		var jwtClient = new google.auth.JWT(
			key.client_email,
			null,
			key.private_key,
			SCOPES,
			null
		);
		jwtClient.authorize(function(err, tokens) {
			if (err) {
				reject(err);
				return;
			}
			resolve(tokens.access_token);
		});
	})
}

var PROJECT_ID = "##############";
var HOST = "fcm.googleapis.com";
var PATH = "/v1/projects/" + PROJECT_ID + "/messages:send";

function sendFcmMessage(fcmMessage) {
	getAccessToken().then(function(accessToken) {
		console.log(accessToken);
		var options = {
			hostname: HOST,
			path: PATH,
			method: 'POST',
			headers: {
				Authorization: "Bearer " + accessToken
			}
		};

		var request = https.request(options, function(resp) {
			resp.setEncoding('utf8');
			resp.on('data', function(data) {
				console.log('Message sent to Firebase for delivery, response: ');
				console.log(data);
			});
		});
		request.on('error', function(err) {
			console.log('Unable to send message to Firebase');
			console.log(err);
		});
		request.write(JSON.stringify(fcmMessage));
		request.end();
	});
}
sendFcmMessage({
	message: {
		token: "######### my token #########",
		data: {
			title:"a",
			message:"b",
			badge:"123"
		}
	}
});
```

don't send a notification message, just use data! Otherwise the system will handle the notification part

**Comment by Wingee** [comment]
@m1ga thank you. That worked - putting it all in data worked for me. It doesn't follow the Google Firebase documentation but it'll do! Thanks for your help

**Comment by m1ga** [comment]
https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages
and also https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages who handles what
