### ISSUE TITLE
Unable to build module

### ISSUE THREAD

**Issue by DCareClues** [hansemannn/titanium-firebase-cloud-messaging#108]
After cloning code and making some changes build is n't happening <img width="709" alt="Screen Shot 2020-04-15 at 2 23 07 PM" src="https://user-images.githubusercontent.com/15869717/79318459-a4e14b80-7f24-11ea-9e03-713f4deef490.png">

Thanks in advance

**Comment by m1ga** [comment]
Do you have Android NDK installed?
`appc ti config android` 
```
android.ndkPath      =  "/home/user/tools/Android/ndk/" 
android.sdkPath      =  "/home/user/tools/Android/sdk/" 
```

Since it is not related to the module I'll close this ticket. Feel free to ask in ti-slack again if the problem still exists after you've checked the NDK paths

**Comment by DCareClues** [comment]
Thanks. Checked, Android NDK isn't installed. Could you tell me which version to install latest showing 21.0.6113669

**Comment by m1ga** [comment]
I didn't update in a while (I'm still using 16)
https://github.com/appcelerator/titanium_mobile/blob/master/android/package.json#L33
is always the best source.

The documentation
https://wiki.appcelerator.org/display/guides2/Installing+the+Android+NDK
says 11+ :-)

**Comment by DCareClues** [comment]
I have installed ndk
<img width="737" alt="Screen Shot 2020-04-15 at 4 05 49 PM" src="https://user-images.githubusercontent.com/15869717/79327977-f690d280-7f32-11ea-8463-38a33cbb15c2.png">

Getting below error
<img width="752" alt="Screen Shot 2020-04-15 at 4 06 14 PM" src="https://user-images.githubusercontent.com/15869717/79328022-0b6d6600-7f33-11ea-9f6c-1d88df2c4f02.png">

**Comment by m1ga** [comment]
wrong ti.playservice version. If you want to use the latest please follow this PR https://github.com/hansemannn/titanium-firebase-cloud-messaging/pull/104 or use version 16.1.4
