### ISSUE TITLE
Cannot build for Android

### ISSUE THREAD

**Issue by Cratyz** [hansemannn/titanium-firebase-cloud-messaging#11]
Im using Titanium SDK @ `7.1.0.GA`. Configuration looks like:
```
<module platform="android" version="1.0.1">firebase.cloudmessaging</module>
<module platform="android" version="2.1.0">firebase.core</module>
```

Results in error message:
```
[ERROR] An error occurred during build after 22s 346ms
[ERROR] Conflicting Android Libraries with package name "com.google.firebase.iid" detected:
[ERROR]   /Users/xx/Library/Application Support/Titanium/modules/android/firebase.cloudmessaging/1.0.1/lib/firebase-iid-11.0.4.aar (hash: 2e2a2bf3cf156227413286f9693ced2390685878, origin: Module)
[ERROR]   /Users/xx/Library/Application Support/Titanium/modules/android/firebase.core/2.1.0/lib/firebase-iid-15.0.0.aar (hash: b0db3336a2ffeebda40a006e15e8dc91dac5e55a, origin: Module)
[ERROR]   
[ERROR] Please either select a version of these modules where the conflicting .aar file is the same or you can try removing the .aar file from one module's "lib" folder.
```

Then, after removing `firebase-iid-11.0.4.aar`, it comes further in the build process but eventually throws:
```
[ERROR] Failed to run dexer:
[ERROR]   
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/firebase/zzb;
[ERROR] 1 error; aborting
```

**Comment by m1ga** [comment]
Use this core version:
https://github.com/hansemannn/titanium-firebase-core/releases/tag/android-2.0.1
the newer version uses 15, this version uses 11.0.4

**Comment by hansemannn** [comment]
https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-1.0.2

**Comment by m1ga** [comment]
I have an app with core 2.0.1 and messaging 2.0.0 which works fine. Please try that combination

**Comment by Cratyz** [comment]
typo? latest is 1.0.2 for `firebase.cloudmessaging`

**Comment by m1ga** [comment]
oh sorry. I had a custom build where I raised the number to 2.0.0! I just looked at my modules folder.

It's https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-1.0.1 with some test code in it :smiley:

**Comment by Cratyz** [comment]
what Ti SDK are you using? If you redownload both

https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-1.0.1
https://github.com/hansemannn/titanium-firebase-core/releases/tag/android-2.0.1

you will get issues. At least thats what I get

**Comment by Cratyz** [comment]
```
Message: Uncaught No static method zzcL(Ljava/lang/String;)Z in class Lcom/google/android/gms/common/util/zzt; or its super classes (declaration of 'com.google.android.gms.common.util.zzt'...
```
cant utilize this combination without runtime errors

**Comment by m1ga** [comment]
```
<modules>
	<module platform="android">ti.playservices</module>
	<module>firebase.core</module>
	<module>firebase.analytics</module>
	<module>firebase.cloudmessaging</module>
</modules>
```
analytics 2.0.1
fcm 1.0.1
core 2.0.1

no error, compiline and working fine :)

**Comment by m1ga** [comment]
@Cratyz using any other module that uses playservices that is NOT using ti.playservices? Like ti.ga, old maps version or so?

**Comment by hansemannn** [comment]
@m1ga With FCM 1.0.2 as well? https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-1.0.2

**Comment by m1ga** [comment]
@hansemannn 

**checked** 
analytics: 2.0.1
fcm: 1.0.2
core: 2.0.1

:heavy_check_mark:  no compiling error
:heavy_check_mark:  sending a notification to the token works fine

BTW: latest analytics 2.1.0 [filename is actually 2.0.2, tag-version is different] crashed the app! But will check that separately
