### ISSUE TITLE
app build failed - android

### ISSUE THREAD

**Issue by bahinapster** [hansemannn/titanium-firebase-cloud-messaging#110]
I am trying to use the 3.0.0 version for android. And i got the following error, does anyone face the same issue ?
SDK 9.0.2 GA

[ERROR] [GRADLE] 
[ERROR] [GRADLE] FAILURE: Build failed with an exception.
[ERROR] [GRADLE] 
[ERROR] [GRADLE] * What went wrong:
[ERROR] [GRADLE] Execution failed for task ':app:mergeDebugJavaResource'.
[ERROR] [GRADLE] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[ERROR] [GRADLE]    > More than one file was found with OS independent path 'firebase-common.properties'
[ERROR] [GRADLE] 
[ERROR] [GRADLE] * Try:
[ERROR] [GRADLE] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[ERROR] [GRADLE] 
[ERROR] [GRADLE] * Get more help at https://help.gradle.org
[ERROR] [GRADLE] 
[ERROR] [GRADLE] BUILD FAILED in 9s

**Comment by Monireb** [comment]
I get the same error with 3.0.0 android version, anybody know how can fix this issue?

Node.js
  Node.js Version             = 12.13.0
  npm Version                 = 6.12.0
Titanium CLI
  CLI Version                 = 5.2.2
Titanium SDK
  SDK Version                 = 9.0.3.GA

**Comment by m1ga** [comment]
`More than one file was found with OS independent path 'firebase-common.properties'`

which modules are you using? You can exclude those files like this https://stackoverflow.com/a/44767574/5193915
```
packagingOptions {
    exclude 'META-INF/DEPENDENCIES'
}
```
but I just saw that people have this error with META-INF files before. I wouldn't exclude any firebase-common files since they might be needed (and I'm not having this error even in bigger projects)

**Comment by Monireb** [comment]
There is no build.gradle file in titanium projects, where should I apply this exclusion?

**Comment by m1ga** [comment]
you create one in `app/platform/android/build.gradle`
