### ISSUE TITLE
didReceiveMessage not working

### ISSUE THREAD

**Issue by infinityofzeroes** [hansemannn/titanium-firebase-cloud-messaging#112]
"FirebaseMessaging: Unable to log event" message after updating Appcelerator SDK 9.1.0
ANDROID and didReceiveMessage suddenly not working. I tried reverting back to old SDK and also not working.
Not sure if it is because of any Android SDK update as I also updated the Android SDK.

**Comment by infinityofzeroes** [comment]
I found the issue... didReceiveMessage event is not working in latest Appcelerator CLI > 8.1.0

**Comment by m1ga** [comment]
working fine for me in 9.1.0.GA with cli 8.1.0 (Androi 10, Pixel 4). Foreground and background

**Comment by hansemannn** [comment]
Same here. Please check your setup or ask for help in [TiSlack](http://ti-slack.org) - this repository is only meant for module bugs.
