### ISSUE TITLE
iOS - Release modules not building when pushed to GH

### ISSUE THREAD

**Issue by perdona** [hansemannn/titanium-firebase-cloud-messaging#123]
We ran into a bug trying to use latest firebase module releases.
Ti (or Xcode) needs the Header folders inside .xcframework to be present in order to successfully build the app.

It works fine if you download the zip locally and build, however, when pushing to github, where empty folders are not tracked, and then checking out, builds fail due to these non-present empty header folders.

It happened with `firebase.core 5.0.0`, `firebase.analytics 4.0.0` and `firebase.cloudmessaging 5.0.0`

**Comment by hansemannn** [comment]
Its a known bug in the Titanium CLI I think. Can you report it to the Appcelerator JIRA please?

**Comment by perdona** [comment]
Hi @hansemannn, thanks for the feedback!

> Its a known bug in the Titanium CLI I think. Can you report it to the Appcelerator JIRA please?
Will do that!

**Comment by m1ga** [comment]
Jira issue: https://jira.appcelerator.org/browse/TIMOB-28511
Github PR: https://github.com/appcelerator/titanium_mobile/pull/12996
since it is merged into the 10.1.0 master I'll close this issue
