### ISSUE TITLE
Event for push notification Click

### ISSUE THREAD

**Issue by karthikTVS** [hansemannn/titanium-firebase-cloud-messaging#129]
Is there any event available for push notification click?

**Comment by hansemannn** [comment]
Please ask questions in TiSlack, thank you!

**Comment by karthikTVS** [comment]
Sorry for the inconvenience. Help us with the slack link thanks.

**Comment by m1ga** [comment]
@karthikTVS https://tislack.org/signup or https://join.slack.com/t/ti-slack/shared_invite/zt-ctkf9ew4-n0j5CCZ02fmJeHmcltxElw for the direct sign-up link
