### ISSUE TITLE
Android 12 Support

### ISSUE THREAD

**Issue by jquick-axway** [hansemannn/titanium-firebase-cloud-messaging#130]
This module will cause an app build failure if the app "targets" Android 12 (aka: API Level 31).

The reason is because Android 12 has a breaking-change where all `<activity/>`, `<receiver/>`, and `<services/>` elements that have an `<intent-filter/>` now require you to define an `android:exported="<true/false>"` attribute.
https://developer.android.com/about/versions/12/behavior-changes-12#security

For this module, you'll need to add an `android:exported="true"` attribute to the following `<service/>` element in the "timodule.xml" file.
https://github.com/hansemannn/titanium-firebase-cloud-messaging/blob/master/android/timodule.xml#L9

**Comment by m1ga** [comment]
Thanks for the check/hint :+1: 
added it, still working fine on Android 11
