### ISSUE TITLE
Example got some probs.

### ISSUE THREAD

**Issue by zenjoe** [hansemannn/titanium-firebase-cloud-messaging#151]
if (OS_IOS) {
	const FirebaseCore = require('firebase.core');
	fc.configure();
  }
**fc is not declared - change to**
if (OS_IOS) {
	const FirebaseCore = require('firebase.core');
	FirebaseCore.configure();
  }
----
Ti.Network.registerForPushNotifications({
		  success: function () {
			  if (!!fcm) {
				  console.log('New token', fcm.fcmToken);
			  }
		  },
**fcm is not declared .. changes to**
Ti.Network.registerForPushNotifications({
		  success: function () {
			  if (!!FirebaseCloudMessaging) {
				  console.log('New token', FirebaseCloudMessaging.fcmToken);
			  }
		  },

**Comment by m1ga** [comment]
Thanks for that. It's fixed. Please make sure the issue is a bit more readable next time :wink: the formatting is a bit messed up

**Comment by zenjoe** [comment]
Yeah sorry - was just about to clean it up :)

Joe Kniesek
