### ISSUE TITLE
Irremovable push bubble appearing over app icon on iOS

### ISSUE THREAD

**Issue by FizixTiramu** [hansemannn/titanium-firebase-cloud-messaging#153]
Hi,

A client has an app that uses push notifications to dispatch alerts. This is working fine, however, iOS has red bubble over the app icon with a notification count of 1 on it. This bubble will not clear, whether we dismiss the alert, clear it, open the app, or whatever.

Is there a way to clear all notification bubbles?

**Comment by m1ga** [comment]
Normally you use `Ti.UI.iPhone.appBadge = 0` to set it back to 0

**Comment by FizixTiramu** [comment]
Thanks for the help, appreciated.
