### ISSUE TITLE
Once the app is in background or closed in android, callback is not fired

### ISSUE THREAD

**Issue by MohamadALHAJJ** [hansemannn/titanium-firebase-cloud-messaging#19]
I've implemented the module as described, all works fine, but once the app is in background or closed the callback is not fired

**Comment by m1ga** [comment]
The notification is visible? The callback is only fired when the app is still available. Otherwise you can get the data when you start your app. See https://github.com/hansemannn/titanium-firebase-cloud-messaging/issues/13#issuecomment-384715757

**Comment by hansemannn** [comment]
Thanks @m1ga, closing! @MohamadALHAJJ Please use StackOverflow for questions, thx!
