### ISSUE TITLE
Notification Tray Slow Response When App Closed on Android

### ISSUE THREAD

**Issue by jwogan5** [hansemannn/titanium-firebase-cloud-messaging#20]
If the app is not running on Android and a notification comes in the user can then tap on the notification tray to open the app.  The app will then take approximately 5 to 6 seconds before it opens.  If the app was minimized and the user taps on the notification tray then the app will open immediately.

**Comment by m1ga** [comment]
Not a module bug

The app is restarting (cold boot) when it is not running.  Should be the same time the app starts when it was killed (so not in background).
