### ISSUE TITLE
Send image in push notification

### ISSUE THREAD

**Issue by yashodeep9** [hansemannn/titanium-firebase-cloud-messaging#21]
I implemented this plugin in android and I am getting push notification in android. Now I want to send image along with push notification title and message, can you please let me know how to do this ? I tried sending image path through Key/Value pair in firebase console where image key was "image", "img_url" which I found through google but there was no success. Please help. Thank you.

**Comment by m1ga** [comment]
Not without changes to the module itself. 
http://androidbash.com/firebase-push-notification-android/
has a tutorial on how to add a remote image.

**Comment by yashodeep9** [comment]
Thanks for your reply.
I think the tutorial is for native implementation and I am integrating it in titanium. I cannot find grade files in titanium

**Comment by m1ga** [comment]
Yes it is a native tutorial, you would have to change the module files:
https://github.com/hansemannn/titanium-firebase-cloud-messaging/tree/master/android/src/firebase/cloudmessaging
and add `Notification messages`.

**Comment by m1ga** [comment]
Remote images and big text coming soon. First test looks promising: 
![screenshot_20180721-182901](https://user-images.githubusercontent.com/4334997/43038102-11966b20-8d14-11e8-9aab-931b6612c10c.png)
Thanks to the good work in ti.goosh I can transfer most of those parts :wink:

**Comment by m1ga** [comment]
https://github.com/hansemannn/titanium-firebase-cloud-messaging/pull/23

**Comment by hansemannn** [comment]
https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-1.2.0 just got released.
