### ISSUE TITLE
createNotificationChannel is not a function

### ISSUE THREAD

**Issue by chee1000** [hansemannn/titanium-firebase-cloud-messaging#22]
unable to call createNotificationChannel

[ERROR] :  TiExceptionHandler: (main) [10,255] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,255] - In /alloy/controllers/index.js:93,17
[ERROR] :  TiExceptionHandler: (main) [0,255] - Message: Uncaught TypeError: cloudMessaging.createNotificationChannel is not a function
[ERROR] :  TiExceptionHandler: (main) [0,255] - Source: 	cloudMessaging.createNotificationChannel();
[ERROR] :  V8Exception: Exception occurred at /alloy/controllers/index.js:93: Uncaught TypeError: cloudMessaging.createNotificationChannel is not a function

**Comment by m1ga** [comment]
which plugin version are you using? And can you show the implementation (just the cludMessaging parts)

**Comment by m1ga** [comment]
sorry, the latest binary was not even released! Check this version:
https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-1.1.0
that includes the notification channel now!

**Comment by chee1000** [comment]
thanks a lot
