### ISSUE TITLE
Android: App will freeze if no default icon is present

### ISSUE THREAD

**Issue by gaspardle** [hansemannn/titanium-firebase-cloud-messaging#28]
If notificationicon is not present in drawable and the `force_show_in_foreground` parameter is used, the module will throw an `java.lang.IllegalArgumentException: Invalid notification (no valid small icon)`, and the app freeze.

**Comment by m1ga** [comment]
I'll add a default icon.

**Comment by m1ga** [comment]
https://github.com/hansemannn/titanium-firebase-cloud-messaging/pull/30
