### ISSUE TITLE
compilation Error after adding this module

### ISSUE THREAD

**Issue by snehalhumne** [hansemannn/titanium-firebase-cloud-messaging#3]
Hi There,

I wanted to integrate the Firebase in our application, But whenever we add this module and try to run the app on the simulator we are facing the compilation error. We are trying to find some solution on it.
Can you please help us on this?

Please find the logs from the Console.
Appcelerator Studio version 5.0.0
Ti SDK: 6.3.0GA
Appc CLI: 6.3.0
Xcode: 9.0.1

Logs from the console while compiling the App:

[TRACE] :  1 warning generated.
[TRACE] :  
[TRACE] :  CompileC build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/TiViewTemplate.o Classes/TiViewTemplate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[TRACE] :      cd /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone
[TRACE] :      export LANG=en_US.US-ASCII
[TRACE] :      export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/bin:/bin:/Users/mindstixsoftwarelabs/Library/apache-ant-1.9.7/bin:/Users/mindstixsoftwarelabs/Library/android-ndk-r13b:/Users/mindstixsoftwarelabs/Documents/Android/home:/Users/mindstixsoftwarelabs/Documents/Android/home/platform-tools"
[TRACE] :      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fmodules -gmodules -fmodules-cache-path=/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wunreachable-code -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wno-parentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEPLOYTYPE=development -DDEBUG=1 -DTI_VERSION=6.3.0 -DTI_LOG_SERVER_PORT=26848 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-unguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/DerivedData/Index/DataStore -iquote /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Connect-generated-files.hmap -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Connect-own-target-headers.hmap -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Connect-all-target-headers.hmap -iquote /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Connect-project-headers.hmap -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/libxml2 -Iheaders -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/DerivedSources/x86_64 -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/DerivedSources -Wno-arc-performSelector-leaks -F/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Products/Debug-iphonesimulator -F/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/modules/iphone/firebase.cloudmessaging/1.0.0/platform -DDEBUG -include /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/PrecompiledHeaders/Connect_Prefix-dkdfaqnxtwplsbanuxcthjysqgdn/Connect_Prefix.pch -MMD -MT dependencies -MF /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/TiViewTemplate.d --serialize-diagnostics /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/TiViewTemplate.dia -c /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/Classes/TiViewTemplate.m -o /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/TiViewTemplate.o
[TRACE] :  
[TRACE] :  CompileC build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/TiSelectedCellbackgroundView.o Classes/TiSelectedCellbackgroundView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[TRACE] :      cd /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone
[TRACE] :      export LANG=en_US.US-ASCII
[TRACE] :      export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/bin:/bin:/Users/mindstixsoftwarelabs/Library/apache-ant-1.9.7/bin:/Users/mindstixsoftwarelabs/Library/android-ndk-r13b:/Users/mindstixsoftwarelabs/Documents/Android/home:/Users/mindstixsoftwarelabs/Documents/Android/home/platform-tools"
[TRACE] :      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fmodules -gmodules -fmodules-cache-path=/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wunreachable-code -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wno-parentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEPLOYTYPE=development -DDEBUG=1 -DTI_VERSION=6.3.0 -DTI_LOG_SERVER_PORT=26848 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Winfinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-unguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/DerivedData/Index/DataStore -iquote /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Connect-generated-files.hmap -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Connect-own-target-headers.hmap -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Connect-all-target-headers.hmap -iquote /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Connect-project-headers.hmap -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/libxml2 -Iheaders -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/DerivedSources/x86_64 -I/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/DerivedSources -Wno-arc-performSelector-leaks -F/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Products/Debug-iphonesimulator -F/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/modules/iphone/firebase.cloudmessaging/1.0.0/platform -DDEBUG -include /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/PrecompiledHeaders/Connect_Prefix-dkdfaqnxtwplsbanuxcthjysqgdn/Connect_Prefix.pch -MMD -MT dependencies -MF /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/TiSelectedCellbackgroundView.d --serialize-diagnostics /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/TiSelectedCellbackgroundView.dia -c /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/Classes/TiSelectedCellbackgroundView.m -o /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/TiSelectedCellbackgroundView.o
[TRACE] :  
[TRACE] :  Ld build/Products/Debug-iphonesimulator/Connect.app/Connect normal x86_64
[TRACE] :      cd /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone
[TRACE] :      export IPHONEOS_DEPLOYMENT_TARGET=8.0
[TRACE] :      export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/bin:/bin:/Users/mindstixsoftwarelabs/Library/apache-ant-1.9.7/bin:/Users/mindstixsoftwarelabs/Library/android-ndk-r13b:/Users/mindstixsoftwarelabs/Documents/Android/home:/Users/mindstixsoftwarelabs/Documents/Android/home/platform-tools"
[TRACE] :      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -L/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Products/Debug-iphonesimulator -L/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/lib -L/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/Classes/APSAnalytics -L/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/Classes/APSHTTPClient -L/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/modules/iphone/firebase.cloudmessaging/1.0.0 -F/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Products/Debug-iphonesimulator -F/Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/modules/iphone/firebase.cloudmessaging/1.0.0/platform -filelist /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/Connect.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/Connect_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -stdlib=libc++ -ObjC -weak-lti_ios_profiler -weak-lti_ios_debugger -weak-lTiCore -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Connect.app.xcent -weak_framework iAd -framework CoreMedia -weak_framework CoreMotion -lAPSAnalytics -weak_framework CoreText -framework EventKit -framework EventKitUI -weak_framework Security -licucore -framework Foundation -weak_framework UIKit -framework CoreGraphics -weak_framework AddressBook -framework AddressBookUI -framework CFNetwork -framework CoreLocation -weak_framework MapKit -framework MessageUI -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -lsqlite3 -lz -framework AudioToolbox -weak_framework MediaPlayer -framework AVFoundation -lxml2 -lAPSHTTPClient -ltiverify -lfirebase.cloudmessaging -framework FirebaseMessaging -Xlinker -dependency_info -Xlinker /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Intermediates/Connect.build/Debug-iphonesimulator/Connect.build/Objects-normal/x86_64/Connect_dependency_info.dat -o /Users/mindstixsoftwarelabs/Perforce/mobile/directAccess/DEV/directAccess-client-6-Dec-17/build/iphone/build/Products/Debug-iphonesimulator/Connect.app/Connect
[TRACE] :  Undefined symbols for architecture x86_64:
[TRACE] :    "_OBJC_CLASS_$_FIRApp", referenced from:
[TRACE] :        objc-class-ref in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :    "_kServiceInfoFileName", referenced from:
[TRACE] :        -[FIRMessaging(FIRApp) exitApp:withError:] in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :    "_kServiceInfoFileType", referenced from:
[TRACE] :        -[FIRMessaging(FIRApp) exitApp:withError:] in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :    "_kFIRServiceMessaging", referenced from:
[TRACE] :        -[FIRMessaging(FIRApp) configureMessaging:] in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :        -[FIRMessaging(FIRApp) exitApp:withError:] in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :    "_kFIRAppIsDefaultAppKey", referenced from:
[TRACE] :        +[FIRMessaging(FIRApp) didReceiveConfigureSDKNotification:] in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :    "_kFIRAppNameKey", referenced from:
[TRACE] :        +[FIRMessaging(FIRApp) didReceiveConfigureSDKNotification:] in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :    "_kFIRAppReadyToConfigureSDKNotification", referenced from:
[TRACE] :        +[FIRMessaging(FIRApp) load] in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :    "_kFirebaseCloudMessagingErrorDomain", referenced from:
[TRACE] :        -[FIRMessaging(FIRApp) configureMessaging:] in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :        -[FIRMessaging(FIRApp) exitApp:withError:] in FirebaseMessaging(FIRMessaging+FIRApp_8f9050f0e621fdb8f1533f65d199228a.o)
[TRACE] :    "_kFIRLoggerMessaging", referenced from:
[TRACE] :        -[FIRMessagingLogger logFuncDebug:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :        -[FIRMessagingLogger logFuncInfo:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :        -[FIRMessagingLogger logFuncNotice:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :        -[FIRMessagingLogger logFuncWarning:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :        -[FIRMessagingLogger logFuncError:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :    "_FIRLogBasic", referenced from:
[TRACE] :        -[FIRMessagingLogger logFuncDebug:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :        -[FIRMessagingLogger logFuncInfo:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :        -[FIRMessagingLogger logFuncNotice:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :        -[FIRMessagingLogger logFuncWarning:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :        -[FIRMessagingLogger logFuncError:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_a242d038850ad1a0d85b3f9a968a56e0.o)
[TRACE] :    "_GPBCheckRuntimeVersionSupport", referenced from:
[TRACE] :        _GtalkGtalkCoreRoot_FileDescriptor in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _GtalkGtalkExtensionsRoot_FileDescriptor in FirebaseMessaging(GtalkExtensions.pbobjc_1632ea94ae068a4c7353857994e00f47.o)
[TRACE] :    "_OBJC_CLASS_$_GPBDescriptor", referenced from:
[TRACE] :        objc-class-ref in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        objc-class-ref in FirebaseMessaging(GtalkExtensions.pbobjc_1632ea94ae068a4c7353857994e00f47.o)
[TRACE] :    "_OBJC_CLASS_$_GPBCodedOutputStream", referenced from:
[TRACE] :        objc-class-ref in FirebaseMessaging(FIRMessagingSecureSocket_9e01de98511ffd1325313fe146c4cf7e.o)
[TRACE] :    "_OBJC_CLASS_$_GPBFileDescriptor", referenced from:
[TRACE] :        objc-class-ref in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        objc-class-ref in FirebaseMessaging(GtalkExtensions.pbobjc_1632ea94ae068a4c7353857994e00f47.o)
[TRACE] :    "_OBJC_METACLASS_$_GPBMessage", referenced from:
[TRACE] :        _OBJC_METACLASS_$_GtalkHeartbeatPing in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_METACLASS_$_GtalkHeartbeatAck in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_METACLASS_$_GtalkErrorInfo in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_METACLASS_$_GtalkSetting in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_METACLASS_$_GtalkHeartbeatStat in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_METACLASS_$_GtalkHeartbeatConfig in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_METACLASS_$_GtalkLoginRequest in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        ...
[TRACE] :    "_OBJC_CLASS_$_GPBEnumDescriptor", referenced from:
[TRACE] :        objc-class-ref in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        objc-class-ref in FirebaseMessaging(GtalkExtensions.pbobjc_1632ea94ae068a4c7353857994e00f47.o)
[TRACE] :    "_OBJC_CLASS_$_GPBMessage", referenced from:
[TRACE] :        _OBJC_CLASS_$_GtalkHeartbeatPing in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_CLASS_$_GtalkHeartbeatAck in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_CLASS_$_GtalkErrorInfo in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_CLASS_$_GtalkSetting in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_CLASS_$_GtalkHeartbeatStat in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_CLASS_$_GtalkHeartbeatConfig in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_CLASS_$_GtalkLoginRequest in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        ...
[TRACE] :    "_OBJC_CLASS_$_GPBRootObject", referenced from:
[TRACE] :        _OBJC_CLASS_$_GtalkGtalkCoreRoot in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_CLASS_$_GtalkGtalkExtensionsRoot in FirebaseMessaging(GtalkExtensions.pbobjc_1632ea94ae068a4c7353857994e00f47.o)
[TRACE] :    "_OBJC_METACLASS_$_GPBRootObject", referenced from:
[TRACE] :        _OBJC_METACLASS_$_GtalkGtalkCoreRoot in FirebaseMessaging(GtalkCore.pbobjc_613b96508ff7f911bb0e8135aace76f5.o)
[TRACE] :        _OBJC_METACLASS_$_GtalkGtalkExtensionsRoot in FirebaseMessaging(GtalkExtensions.pbobjc_1632ea94ae068a4c7353857994e00f47.o)
[TRACE] :    "_OBJC_CLASS_$_FIRReachabilityChecker", referenced from:
[TRACE] :        objc-class-ref in FirebaseMessaging(FIRMessaging_525e41c3f6cf74170293c90cab286e83.o)
[TRACE] :  ld: symbol(s) not found for architecture x86_64
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] :  2018-03-03 00:25:31.018 xcodebuild[5150:46080] WARNING: Failed to load plugin at path: "/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin/Contents/MacOS/CComment): no suitable image found.  Did find:
[ERROR] :  	/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin/Contents/MacOS/CComment: code signing blocked mmap() of '/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin/Contents/MacOS/CComment'
[ERROR] :  	/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin/Contents/MacOS/CComment: stat() failed with errno=1" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin/Contents/MacOS/CComment, NSDebugDescription=dlopen_preflight(/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin/Contents/MacOS/CComment): no suitable image found.  Did find:
[ERROR] :  	/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin/Contents/MacOS/CComment: code signing blocked mmap() of '/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin/Contents/MacOS/CComment'
[ERROR] :  	/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin/Contents/MacOS/CComment: stat() failed with errno=1, NSBundlePath=/Users/mindstixsoftwarelabs/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CComment.xcplugin, NSLocalizedDescription=The bundle “CComment” couldn’t be loaded because it is damaged or missing necessary resources.}
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/Products/Debug-iphonesimulator/Connect.app/Connect normal x86_64
[ERROR] :  (1 failure)

**Comment by KunalBonage** [comment]
Any Updates on this? We are also facing the same issue.

**Comment by hansemannn** [comment]
What modules do you have in your tiapp.xml? Likely you are missing the firebase.core module which is explicitly required in the readme.

**Comment by KunalBonage** [comment]
Thanks it's working.

**Comment by hansemannn** [comment]
Please read the readme guys. Those issues are extremely time consuming to maintain.
