### ISSUE TITLE
App in background: Notification is received but app is closed on clicking notification tray

### ISSUE THREAD

**Issue by apurvaAndroid** [hansemannn/titanium-firebase-cloud-messaging#31]

**Comment by apurvaAndroid** [comment]
Working fine in below scenarios:
1.App is killed and push notification arrives.
2.App is in foreground and push notification arrives.

Not working when App is in background and push notification arrives.

**Comment by apurvaAndroid** [comment]
var core = require('firebase.core');
			var fcm = require('firebase.cloudmessaging');
			var isAndroid = Ti.Platform.osname === 'android';
			
			// Configure core module (required for all Firebase modules)
			
			core.configure({
				APIKey:'YourAPI KEY',
				googleAppID : 'APPID',
				GCMSenderID : 'GCMSenderID',
				applicationID: "applicationID"
		    });

		    	fcm.addEventListener('didRefreshRegistrationToken', onToken);
			
			// Called when direct messages arrive. Note that these are different from push notifications
			fcm.addEventListener('didReceiveMessage', onMessage);
			
			fcm.registerForPushNotifications();
			
			 fcm.addEventListener('didReceiveMessage', function (e) {
	            //Ti.API.info('!!!!!!Message ', JSON.stringify(e));
	          
	            
				
       		 });
			
			function onToken(e) {
			    Ti.API.info('Token', e.fcmToken);
			    Alloy.Globals.DeviceToken = e.fcmToken;

			}
			
			function onMessage(e) {
			    Ti.API.info('Message', e.message);
			}

			isAndroid && fcm.createNotificationChannel({
				  sound: 'warn_sound',
				  channelId: 'general',
				  channelName: 'General Notifications',
				  importance: 'high' //will pop in from the top and make a sound
				});

		     if (fcm.fcmToken !== null) {
			 Alloy.Globals.DeviceToken = fcm.fcmToken;

			    Ti.API.info('FCM-Token', fcm.fcmToken);
			} else {
			    Ti.API.info('Token is empty. Waiting for the token callback ...');
			}

			 fcm.subscribeToTopic('testTopic');

-------
format of payload

{"to":"fvfEay1N-ss:APA91bFx1UTmDwGgpa0Oic63O48_PhMN7xi8h1E9FAy353T4wm-v4VKvyablAtVqlj1kEWcsmfp6qy-1cbDa7pXIIQi2Blc-P7dQhHPb71ciieLvneYTMZRvKXB7S1xPqPV8GqzFkepz","notification":{"title":"Working Good","body":"[add your message]"} "data":{ "type":"req"},"priority":"high"}

**Comment by m1ga** [comment]
try removing the 2nd ` fcm.addEventListener('didReceiveMessage', function (e) {...}`

and use `lastData` since you are sending a notification and data.

**Comment by apurvaAndroid** [comment]
Removed fcm.addEventListener('didReceiveMessage', function (e) {...}

                        function onMessage(e) {
			    Ti.API.info('ON __ Message', JSON.stringify(e));
			}
Done the changes still facing same issue.

**Comment by m1ga** [comment]
btw: what is not working? You've just said `Not working when App is in background and push notification arrives.`
Is the app not opening? Do you not get the data (again use `lastData`)?

**Comment by apurvaAndroid** [comment]
When the app is in the background and I received a push notification but the app crashed when I click on notification tray

**Comment by m1ga** [comment]
so anything in the log when it crashes?

**Comment by apurvaAndroid** [comment]
10-26 11:23:28.465: W/FirebaseMessaging(29463): Error while parsing timestamp in GCM event
10-26 11:23:28.465: W/FirebaseMessaging(29463): java.lang.NumberFormatException: s == null
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at java.lang.Integer.parseInt(Integer.java:570)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at java.lang.Integer.valueOf(Integer.java:794)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at com.google.firebase.messaging.zzd.zzb(Unknown Source:60)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at com.google.firebase.messaging.zzd.zzh(Unknown Source:84)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at com.google.firebase.messaging.FirebaseMessagingService.zzo(Unknown Source:35)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at com.google.firebase.iid.zzf.zza(Unknown Source:38)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at com.google.firebase.iid.zzh.zzJO(Unknown Source:80)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at com.google.firebase.iid.zzh.zza(Unknown Source:29)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at com.google.firebase.iid.FirebaseInstanceIdInternalReceiver.onReceive(Unknown Source:41)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3392)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at android.app.ActivityThread.-wrap18(Unknown Source:0)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at android.os.Looper.loop(Looper.java:164)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at java.lang.reflect.Method.invoke(Native Method)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
10-26 11:23:28.465: W/FirebaseMessaging(29463): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
10-26 11:23:28.466: W/FirebaseMessaging(29463): Unable to log event: analytics library is missing
10-26 11:23:28.466: D/ViewRootImpl@c7de49b[getattendantapp](3254): setView = DecorView@4cc2f77[getattendantapp] TM=true MM=false
10-26 11:23:28.471: D/MdnieScenarioControlService(3254): Listener Real Multi Window State : false
10-26 11:23:28.471: D/CodecSolution(3254): MultiWindowEventListener::onMultiWindowFocusChanged(1)

**Comment by apurvaAndroid** [comment]
Who is facing background notification issue please use below module 

[firebase.cloudmessaging-android-1.5.0.zip](https://github.com/hansemannn/titanium-firebase-cloud-messaging/files/2534820/firebase.cloudmessaging-android-1.5.0.zip)
TI.SDK 7.1.1

**Comment by m1ga** [comment]
What did you change? Anything that can be included in the public module?

**Comment by antonioduran** [comment]
Hey hello @apurvaAndroid . This module version (https://github.com/hansemannn/titanium-firebase-cloud-messaging/files/2534820/firebase.cloudmessaging-android-1.5.0.zip)  in my case it is working sending push notifications through onesignal, the other version of the module like (Android 1.4.0) is not working at all -  but ned to know whether you found something tho get the data when the app is closed, and the push notification arrives. I mean to get the information of the payload when we click on the push notification from the notification tray. I appreciate any information. Thank you.

**Comment by antonioduran** [comment]
Hey hello @apurvaAndroid . This module version (https://github.com/hansemannn/titanium-firebase-cloud-messaging/files/2534820/firebase.cloudmessaging-android-1.5.0.zip)  in my case your module it is working sending push notifications through onesignal, the other version of the module like (Android 1.4.0) is not working at all -  but need to know whether you found something to get the data when the app is closed, and the push notification arrives. I mean to get the information of the payload when we click on the push notification from the notification tray. I appreciate any information. Thank you.

**Comment by apurvaAndroid** [comment]
@antonioduran no I have not found payload on clicking of notification tray.

**Comment by aseemk98** [comment]
Even I'm getting the same error when I'm trying to log the contents of the message. When, I close the app, the message shows up in the notification tray but the error "Unable to log event: analytics library is missing" is displayed in the logcat. How do I fix it?
