### ISSUE TITLE
App in background: Tapping on Notification how to get callback

### ISSUE THREAD

**Issue by DCareClues** [hansemannn/titanium-firebase-cloud-messaging#33]
I want to redirect to specific pages on tap of notification. When app is in killed state redirection is happening fine as I am getting callback via ```Ti.Android.currentActivity.getIntent().``` on alloy.js. When App is in background, tapping on notification it opens the app, how to know app is resuming from notification as well as how to get data.

**Comment by m1ga** [comment]
when the app is still running in background you'll receive the `didReceiveMessage` event and can use that to open the page

**Comment by DCareClues** [comment]
```didReceiveMessage ``` is only for IOS, is there any event for Android?

**Comment by m1ga** [comment]
the same. Just try the example https://github.com/hansemannn/titanium-firebase-cloud-messaging#example

**Comment by DCareClues** [comment]
I tried. ```didReceiveMessage``` called when direct messages arrive, not when notification tapped. I want to open specific page when app is in background and notification is tapped. Please help.

**Comment by DCareClues** [comment]
IOS it is working as expected. On Android device on tap resumes the app, not getting callback https://drive.google.com/drive/folders/1t6f50sMMIrMBaspxF8ab-o35_JW5FHvc?usp=sharing.  I am using postman to send direct message.  Is it require any other configuration?

**Comment by m1ga** [comment]
But the alert is appearing in your video so the app recognizes the push! It is already showing because the app is still running in background. 
So you have to use the pause/resume to know when you are back in the app. Or try to see if 
```
var act = Titanium.Android.currentActivity;
var _intent = act.intent;
console.log(_intent.getStringExtra("test1"));
console.log(_intent.getStringExtra("test2"));
```
is filled. But I'm not sure if you get any info from the notification click when you go back into the app from background

**Comment by DCareClues** [comment]
Tried above code on focus event, intent is not filled. pause/resume not working on android :(

**Comment by m1ga** [comment]
I've tweak `lastData` in https://github.com/hansemannn/titanium-firebase-cloud-messaging/pull/36 and did some testing yesterday with different notification types and resuming. 

Proper resume events are part of Ti 7.5.0 but you can use https://www.tidev.io/2014/01/28/paused-resumed-events-on-android/ `bencoding.android.tools`. If you want to use the current activity only have a look at https://gist.github.com/kristjanmik/aefc77b5b05e792ecdd2 Thats what I've used for testing.

**Comment by DCareClues** [comment]
Thank you so much for taking up this request. I am waiting this to be merged in master so that I can use it in my app.

**Comment by m1ga** [comment]
new version released, please test it

**Comment by m1ga** [comment]
@kerbooo did you try `lastData`?

**Comment by kerbooo** [comment]
is there any example for using lastData? I didn't find.

**Comment by m1ga** [comment]
you are right, need to add that to the example. Try this please:

```
function checkIntent() {
	var act = Titanium.Android.currentActivity;
	var _intent = act.intent;
	console.log("data", _intent.getData());
	console.log("data data", _intent.getStringExtra("data"));
	console.log("fcm_data", _intent.getStringExtra("fcm_data"));
	console.log(fcm.lastData);
}

$.index.addEventListener("open", function() {
	checkIntent()
	if (this.activity) {
		this.activity.onResume = function() {
			checkIntent()
		};
	} else {
		Ti.App.addEventListener("resumed", function() {
			checkIntent()
		});
	}
});
```

**Comment by kerbooo** [comment]
Thank you very much. I am trying to get **lastData** for android the following

`FirebaseCloudMessaging.lastData`

It returns data but I would like check **lastData** is empty or not? When I am using as below 

```
var _LastData = JSON.stringify(FirebaseCloudMessaging.lastData);

if (_LastData != "{}") {
....
}
```

It does not return correct result every time. is there any way to check FirebaseCloudMessaging.lastData is empty or not?

**Comment by m1ga** [comment]
can't test it at the moment, but just check if your data is in or the length is 1 or 0 (I think `inBackground` is always in).

**Comment by hansemannn** [comment]
```js
if (Object.keys(FirebaseCloudMessaging.lastData).length === 0) {
  // No data
}
```
Please refer to the Firebase docs on when it will be available and when not.

**Comment by kerbooo** [comment]
@hansemannn I am sorry I am late for answer the result. Yes the following codes are working. Thank you very much.

```

if (Object.keys(FirebaseCloudMessaging.lastData).length === 0) {
  // No data
}
```
 But I am having problem on iOS for manipulating screen.  Message arrives to device but I am not getting payload value.

```
fcm.addEventListener('didReceiveMessage', function(e) {
    Ti.API.info('Message', e.message);
});
```

**Comment by kerbooo** [comment]
@hansemannn Hi again I achieved for manipulating screen on iOS with callback function as below  

```
  Ti.Network.registerForPushNotifications({
    success: function () {},
    error: function () {},
    callback: function () { 

 } 
  });
```
Thank you for your support
