### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by Wingee** [hansemannn/titanium-firebase-cloud-messaging#4]
Any idea when the Android version will be available? Or suggestions for an alternative module that will work with SDK 7.x ?

**Comment by hansemannn** [comment]
No, not planned. Its a community driven project, so feel free to implement the change for you and others.

**Comment by Wingee** [comment]
Thanks, if only it was community driven, it seems like you're the only one contributing to it!

**Comment by mattberg** [comment]
In desperate need of Android version also :)

**Comment by m1ga** [comment]
Started a port: https://github.com/hansemannn/titanium-firebase-cloud-messaging/pull/6
not fully wokring yet :-( But I'm already getting a token ;)

**Comment by hansemannn** [comment]
Closing as part of the Android release scheduled for today.

**Comment by hansemannn** [comment]
-> https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-1.0.0
