### ISSUE TITLE
Is there a way to check notification status?

### ISSUE THREAD

**Issue by Abdelalim-dev** [hansemannn/titanium-firebase-cloud-messaging#40]
I would like to check if the user has disabled notifications in the settings app.
This feature is available in **ti.goosh** as a method `areNotificationsEnabled()`.

**Comment by m1ga** [comment]
not yet, but feel free to create a PR to include it
https://github.com/caffeinalab/ti.goosh/blob/879f411b171dd591e609d5f6c8254e0c49e6d951/android/src/ti/goosh/TiGooshModule.java#L157

**Comment by Abdelalim-dev** [comment]
Thank you for sharing @hansemannn 
I noticed something weird though!
The docs say that this method should be available on Android 7.1.0+ but it worked fine when I tried it on Android 5.1!!

**Comment by m1ga** [comment]
ah, even better. I though that there is something FCM related that needs to be implemented

**Comment by Abdelalim-dev** [comment]
I guess we can close this issue now that the solution suggested by @hansemannn works fine.
> Or `Ti.Android.NotificationManager.areNotificationsEnabled()` from the SDK?
