### ISSUE TITLE
Error on notification click

### ISSUE THREAD

**Issue by Abdelalim-dev** [hansemannn/titanium-firebase-cloud-messaging#41]
I receive notifications normally when the app is in background but when I click on them I get the following error:
`TiLaunchActivity: (main) [16,187642] Android issue 2373 detected (missing intent CATEGORY_LAUNCHER or FLAG_ACTIVITY_RESET_TASK_IF_NEEDED), restarting app.`
I even tried the modified version of the module from #31 but I had the same issue.
Here's the screen I get when the error occurs: https://ibb.co/XkjSvrm

**PS: I looked everywhere before adding this issue.**

**Comment by m1ga** [comment]
add this to your tiapp.xml
```
 <property name="ti.android.bug2373.finishfalseroot" type="bool">true</property>
```
(it's mentioned inside the appc docu).

Beginning of 8.0.0 you probably won't need this as they rewrite the app resume (https://github.com/appcelerator/titanium_mobile/pull/10519)

**Comment by Abdelalim-dev** [comment]
Thank you @m1ga , this fixed the issue. Closing...
**PS**: Although the app was in the background it some time to start as if it was killed. Any hint to why that might be?
