### ISSUE TITLE
[ERROR] :  TiExceptionHandler: (main) [1959,12422] No static method zzrU()Lcom/google/android/gms/common/stats/zza;

### ISSUE THREAD

**Issue by blantonl** [hansemannn/titanium-firebase-cloud-messaging#42]
On receipt of a push notification on Android, I receive the following error:

[ERROR] :  TiExceptionHandler: (main) [1959,12422] No static method zzrU()Lcom/google/android/gms/common/stats/zza;

Titanium SDK 7.5.0.GA

Modules:

ti.playservices 11.0.40
firebase.core  3.0.0
firebase.cloudmessaging 1.3.2
ti.admob 4.4.0

Probably a Google Play Services conflict?  Any ideas on how to resolve?

**Comment by hansemannn** [comment]
Make sure to specify Ti.PlayServices 11.0.40 in your tiapp.xml when using firebase-cloud 1.x.
