### ISSUE TITLE
App closed, how to get the data?

### ISSUE THREAD

**Issue by caspahouzer** [hansemannn/titanium-firebase-cloud-messaging#44]
Hi,

if my app is closed and a push message with data fields arrive... How to get the data on tap the notification?

`lastData` seems to be empty

**Comment by m1ga** [comment]
you could check the intent
```
function checkIntent() {
	var act = Titanium.Android.currentActivity;
	var _intent = act.intent;
	console.log("data", _intent.getData());
	console.log("data data", _intent.getStringExtra("data"));
	console.log("fcm_data", _intent.getStringExtra("fcm_data"));
	console.log(fcm.lastData);
}

$.index.addEventListener("open", function() {
	checkIntent()
	if (this.activity) {
		this.activity.onResume = function() {
			checkIntent()
		};
	} else {
		Ti.App.addEventListener("resumed", function() {
			checkIntent()
		});
	}
});
```

**Comment by antonioduran** [comment]
"+1" .Hello @caspahouzer. I am getting the same issue. I noticed that if the logic is not in the index.js, you will see that the `lastData` is empty. Perpahs, it will be great to have a callback in the module to get the information also from background.

**Comment by hansemannn** [comment]
Closing since this is rather a question than a bug.
