### ISSUE TITLE
App Name not showing up on notification

### ISSUE THREAD

**Issue by rahul2tiw** [hansemannn/titanium-firebase-cloud-messaging#46]
Hi,

I have been able to configure the notification through Localytics and Firebase and your 

> Setting the Notification Icon 
did help a lot in setting the notification icon . But I am not able to include app name in the notifications in android when I trigger a message from localytics.

Your help will be really appreciated @hansemannn

**Comment by hansemannn** [comment]
This is a question about the configuration and not a module bug. Please use StackOverflow or TiSlack for general questions.
