### ISSUE TITLE
Android: tapping on a notification message while in foreground

### ISSUE THREAD

**Issue by Jei** [hansemannn/titanium-firebase-cloud-messaging#52]
I'm having some problems handling notification and mixed messages.
While the app is closed or in background, notifications are viewed in the tray, and they "restart" the app when tapped. However, if I tap on a notification while the app is in foreground, the launcher is opened again and then nothing happens. The app gets stuck on the launcher screen.

As I understand, this issue is related to how activity stacks are handled by Android and Titanium, but I really don't know how to change this behavior in a way that will simply keep the current stack and activity open if the app is in foreground.

**Comment by antonioduran** [comment]
+ 1 . Hello @Jei I am getting the same...In my case, some times this is only happening at the beginning in a fresh installed app. I open the push notification and the app gets stuck also. I will try to add more details about it.

**Comment by Jei** [comment]
I found out that I was using a RC version of Ti 7.5.1 that didn't have this fix https://jira.appcelerator.org/browse/TIMOB-26774
Basically, that PR restored the previous behavior of Titanium apps on Android, which was to run app.js each time an Activity stack is created. This solves the issue of apps being stuck on the launch screen when called by an intent while backgrounded.

The solution is to use Titanium 7.5.1.GA, released today.

![download 3](https://user-images.githubusercontent.com/1693076/53485641-0297a780-3a87-11e9-8f34-842669e44919.jpeg)
