### ISSUE TITLE
Android 9 -Failed to start service while in background - 7.5.0.GA

### ISSUE THREAD

**Issue by antonioduran** [hansemannn/titanium-firebase-cloud-messaging#53]
Hello. Good afternoon. I noticed this issue. 

Titanium SDK 7.5.0.GA
Device: Huawei P20 PRO
Android version : 9

When the screen of the mobile device is off, and I try to install the app with this module of firebase-cloud-messaging with titanium-firebase-core; I am getting the following:

https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-1.4.0
https://github.com/hansemannn/titanium-firebase-core/releases/tag/android-3.0.2

[ERROR] FirebaseInstanceId: Failed to start service while in background: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.firebase.INSTANCE_ID_EVENT pkg=com.tony.tony cmp=com.tony.tony/firebase.cloudmessaging.TiFirebaseInstanceIDService (has extras) }: app is in background uid UidRecord{709d7a u0a229 TPSL idle procs:1 seq(0,0,0)} 

so this is prouducing the 
02-19 13:27:57.693 28810-28810/? I/TiAPI:  Token is empty. Waiting for the token callback ...

Thanks, and best,
Antonio.

**Comment by kerbooo** [comment]
Hello I am really have issue and I need help about this issue [https://jira.appcelerator.org/plugins/servlet/mobile#issue/AC-6141](https://jira.appcelerator.org/plugins/servlet/mobile#issue/AC-6141)

**Comment by hansemannn** [comment]
Make sure to specify Ti.PlayServices 11.0.40 in your tiapp.xml when using  firebase-cloud 1.x.
