### ISSUE TITLE
Android: Vibration

### ISSUE THREAD

**Issue by m1ga** [hansemannn/titanium-firebase-cloud-messaging#56]
Need to test the vibration settings for Android

* According to https://stackoverflow.com/a/49283420/5193915 you have to enable it for each channel:
https://github.com/hansemannn/titanium-firebase-cloud-messaging/blob/3ce5abc6a6f8aa4c9d16adb048bb90a094b17f7d/android/src/firebase/cloudmessaging/CloudMessagingModule.java#L201
* add `<uses-permission android:name="android.permission.VIBRATE"/>` to the module
* look at the custom vibration scheme from ti.goosh: https://github.com/caffeinalab/ti.goosh/blob/6e33ba9d730b0854b7727d405e3f82cef7ab7b60/android/src/ti/goosh/IntentService.java#L273
* update the example

**Comment by m1ga** [comment]
already have it working! `builder.setDefaults(Notification.DEFAULT_ALL);` is missing too

**Comment by hansemannn** [comment]
Added via #57
