### ISSUE TITLE
Build with ti.playservices 16.1.2 causes ClassNotFoundExcepion

### ISSUE THREAD

**Issue by sandrolain** [hansemannn/titanium-firebase-cloud-messaging#58]
Compiling with the latest default version of ti.playservices the following error occurs:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbo;
```

It is necessary to specify the previous version 11.0.40 of the module

```
<module platform="android" version="11.0.40">ti.playservices</module> 
```

**Comment by hansemannn** [comment]
#51 is nearly finished and adds full compatibility with Play Services 16.x!
