### ISSUE TITLE
Support to have parity with onesignal payload - alert field for the subtitle of a push notification

### ISSUE THREAD

**Issue by antonioduran** [hansemannn/titanium-firebase-cloud-messaging#60]
Hello @m1ga  @hansemannn . Good afternoon / evening.

I had to migrate from onesignal module to this module, you know for the reason of support, and new migration to firebase.

I noticed  when onesignal sends to push notification from its web manager, the push notification is just displaying the title, and the subtitle of the push notification is not appearing, this behavior is due to the following:

Example of payload sent by onesignal
`03-05 16: 06: 43.725 2206-2834 /? D / FirebaseMsgService: Data message: {custom = {"i": "5fbbf372-6d41-447a-9dab-1186168911a1"}, oth_chnl =, pri = 5, vis = 1, alert = desc, title = title, grp_msg =} `

So, currently the module of TiFirebase can catchs the title field, and body field  to display the title, and subtitle of a push notification, but as you can see in the above payload onesignal is sending the alert field for the description which the modue can not catch this part because is waiting the field of body.
(https://github.com/hansemannn/titanium-firebase-cloud-messaging/blob/master/android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java#L64)

I noticed that the module is using an aar file (https://github.com/hansemannn/titanium-firebase-cloud-messaging/tree/master/android/lib/firebase-messaging-11.0.4.aar
), so I unzipped the file modifying the extension, so that I can get the files, and I noticed that there is a class.jar file, which it has all the clases, but I could not modify the specific classes inside of the .jar file, so that we can implement the change to display the subtitle of the push notification getting the alert field from onesignal, since the logic of the module it says that the module will get the body field from the payload for the subtitle.

My question is whether it could exist the possibility to have the classes from the jar file, so that we can edit/add this specific field (alert) with the setter/getter so that if someone is sending push notifications through one signal portal or api; the subtitle can be appearing.

Please let me know if you have any doubt or question.

Thanks, and best,
Antonio

**Comment by m1ga** [comment]
Hi, since it is sending a data message line 64 is ignored. The real part is here:
https://github.com/hansemannn/titanium-firebase-cloud-messaging/blob/master/android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java#L131
there it is using `title` and `message`. In you case it should check `params.get("alert")` too and use that as a message (e.g. if `message` is empty). Correct?
At least for Android that would be not that difficult.

**Comment by antonioduran** [comment]
Hey hello @m1ga. Good afternoon / evening.
Thank you man. I did not notice that part in the TiFirebaseMessagingService.java#L131, but it worked with your suggestion, now the push notification is displaying the subtitle.

I owe you one.

Have great days. Thank you again man.

**Comment by fahad86** [comment]
@m1ga do you think the solution provided for this could be made universal?

**Comment by m1ga** [comment]
@fahad86 in Version 1.5.0 the `alert` field was added. So it should already work with the latest module.
