### ISSUE TITLE
How can I catch event 'click' on push-message?

### ISSUE THREAD

**Issue by mirash8842** [hansemannn/titanium-firebase-cloud-messaging#62]
How can I catch event 'click' on push-message in Android? In 'ti.goosh' function 'gcm.registerForPushNotifications' has method "callback". In 'callback' I put function. This function  starts when the user clicks on the push-notification. How can I do this with firebase-cloud-messaging?

**Comment by m1ga** [comment]
according to ti.goosh it is `// The callback to invoke when a notification arrives.` so this will be the `fcm.addEventListener('didReceiveMessage' ,function())` event here

**Comment by mirash8842** [comment]
Thank you very much for the answer, but with the "ti.goosh" module I could start the function by clicking on the notification when the application is minimized. Just like this:
var gcm = require('ti.goosh');
	gcm.registerForPushNotifications({
	    callback: function(e) {
               MyFunction();
          }
In this module, when you click on the notification, the application simply opens and "fcm.addEventListener ('did Receive Message', onMessage)" does not work

**Comment by m1ga** [comment]
works fine here:
```
fcm.addEventListener("didReceiveMessage", onMessage);
function onMessage(e) {
	console.log("Got message");
	alert("Got message: " + JSON.stringify(e.message.data));
}
```

app minimized. Push arrives. Clicking the push to open the app. App starts, alert and console log are shown.

Android 7 on device

**Comment by mirash8842** [comment]
Unfortunately this code does not work for me. The 'onMessage' function only works if the app is already open in full screen.
Android Emulator Pixel_2_XL_API_28 and device Nexus 5 (android 6.0.1)

**Comment by m1ga** [comment]
please show your push message that you are sending. I'm using all the things from the example in the Readme and it works fine.

**Comment by mirash8842** [comment]
I use this code on Ruby on Rails for testing.
```
begin
   push = Push.create!(
          {
            :user_id => user.id,
            :os_name => :android,
            :title   => title,
            :content => data.to_json,
            :category => category,
            :device_token => user.android_appid
          }
        )
        data[:data][:push_id] = push.id

          notdat =
          {
            :notification =>
            {
              :title => 'NotificationDataTitle',
              :body =>  'NotificationDataBody'
            },
            :data =>
            {
              :title => 'DataNotificationTitle',
              :message =>  'DataNotificationMessage',
              :force_show_in_foreground => true,
              :id => push.id,
              :color => '#c4ae67'
            }
          }
        r = fcm.send(registration_id, notdat)
    
    rescue Exception => ex
        Rails.logger.info "!!!!!!!!! push error - ex = #{ex.message}"
        nil
      end
   end
 end
```
If the app is already open in full screen, I receive 'DataNotificationTitle' and 'DataNotificationMessage'.
If the app is minimized, I receive 'NotificationDataTitle' and  'NotificationDataBody'

**Comment by m1ga** [comment]
try sending just the data notification.

**Comment by mirash8842** [comment]
It works. Thanks a lot.
