### ISSUE TITLE
iOS: subscribeToTopic(topic) not work

### ISSUE THREAD

**Issue by nadjib** [hansemannn/titanium-firebase-cloud-messaging#64]

**Comment by hansemannn** [comment]
Missing details, logs and versions.

**Comment by nadjib** [comment]
> Missing details, logs and versions.

I can give `fcm.fcmToken` but `fcm.subscribeToTopic('testTopic')` not work with me, the device not subscribe in topic, i check with this :
[https://iid.googleapis.com/iid/info/FCM_TOKEN?details=true](https://iid.googleapis.com/iid/info/FCM_TOKEN?details=true)

This is my code (iOS only) :
`
// Firebase
var core = require('firebase.core');
var fcm = require('firebase.cloudmessaging');

// Configure core module (required for all Firebase modules).
core.configure({
    file: 'GoogleService-Info.plist'
});

// Called when direct messages arrive. Note that these are different from push notifications.
fcm.addEventListener('didReceiveMessage', function(e) {
    Ti.UI.createAlertDialog({
		message: e.message,
		ok: L('ok')
	}).show();
});

Ti.App.iOS.addEventListener('usernotificationsettings', function eventUserNotificationSettings() {
    // Remove the event again to prevent duplicate calls through the Firebase API
    Ti.App.iOS.removeEventListener('usernotificationsettings', eventUserNotificationSettings);

    // Register for push notifications
    Ti.Network.registerForPushNotifications({
        success: function () {},
        error: function () {},
        // Fired for all kind of notifications (foreground, background & closed)
        callback: function (e) {  		
        		var data = e.data;
	        	Ti.UI.createAlertDialog({
				message: data.aps.alert.body,
				title: data.aps.alert.title,
				ok: L('ok')
			}).show();
    		}
    });
});

// Register for the notification settings event
Ti.App.iOS.registerUserNotificationSettings({
    types: [
        Ti.App.iOS.USER_NOTIFICATION_TYPE_ALERT,
        Ti.App.iOS.USER_NOTIFICATION_TYPE_SOUND,
        Ti.App.iOS.USER_NOTIFICATION_TYPE_BADGE
    ]
});

// Register the device with the FCM service.
fcm.registerForPushNotifications();

// Check if token is already available.
if (fcm.fcmToken)
    Ti.API.info('FCM-Token', fcm.fcmToken);
else
    Ti.API.info('Token is empty. Waiting for the token callback ...');

// Subscribe to topic
fcm.subscribeToTopic('testTopic');
`

Versions:
firebase.core: 2.2.0
firebase.cloudmessaging: 2.0.1
