### ISSUE TITLE
iOS: subscribeToTopic(topic) not work

### ISSUE THREAD

**Issue by nadjib** [hansemannn/titanium-firebase-cloud-messaging#65]
I can give `fcm.fcmToken` but `fcm.subscribeToTopic('testTopic')` not work with me, the device not subscribe in topic, i check with this :
[https://iid.googleapis.com/iid/info/FCM_TOKEN?details=true](https://iid.googleapis.com/iid/info/FCM_TOKEN?details=true)

This is my code (iOS only) :
```
// Firebase
var core = require('firebase.core');
var fcm = require('firebase.cloudmessaging');

// Configure core module (required for all Firebase modules).
core.configure({
    file: 'GoogleService-Info.plist'
});

// Called when direct messages arrive. Note that these are different from push notifications.
fcm.addEventListener('didReceiveMessage', function(e) {
    Ti.UI.createAlertDialog({
		message: e.message,
		ok: L('ok')
	}).show();
});

Ti.App.iOS.addEventListener('usernotificationsettings', function eventUserNotificationSettings() {
    // Remove the event again to prevent duplicate calls through the Firebase API
    Ti.App.iOS.removeEventListener('usernotificationsettings', eventUserNotificationSettings);

    // Register for push notifications
    Ti.Network.registerForPushNotifications({
        success: function () {},
        error: function () {},
        // Fired for all kind of notifications (foreground, background & closed)
        callback: function (e) {  		
        		var data = e.data;
	        	Ti.UI.createAlertDialog({
				message: data.aps.alert.body,
				title: data.aps.alert.title,
				ok: L('ok')
			}).show();
    		}
    });
});

// Register for the notification settings event
Ti.App.iOS.registerUserNotificationSettings({
    types: [
        Ti.App.iOS.USER_NOTIFICATION_TYPE_ALERT,
        Ti.App.iOS.USER_NOTIFICATION_TYPE_SOUND,
        Ti.App.iOS.USER_NOTIFICATION_TYPE_BADGE
    ]
});

// Register the device with the FCM service.
fcm.registerForPushNotifications();

// Check if token is already available.
if (fcm.fcmToken)
    Ti.API.info('FCM-Token', fcm.fcmToken);
else
    Ti.API.info('Token is empty. Waiting for the token callback ...');

// Subscribe to topic
fcm.subscribeToTopic('testTopic');
```

**Versions:**
- firebase.core: 2.2.0
- firebase.cloudmessaging: 2.0.1

**Comment by caspahouzer** [comment]
Same problem here. Android topic subscriber are receiving the pushes, iOS don't

**Comment by qalbit** [comment]
Same problem. Any update on this?

**Comment by hansemannn** [comment]
@caspahouzer Direct messages are meant for a chat functionality. You can send single messages using the registration-id. Since we don't use direct messages internally, there is no immediate plan to work on this. Please make yourself familiar with the code or consult someone to look into it.

**Comment by roelandp** [comment]
@hansemannn I also found this "bug". As per Cloudmessage' console, one can send messages based on topic. Or based on device type. This feature is thus not limited to "direct messaging". 

Although I seem to be able to create 'topics' for android users, and target them instantly by sending a cloudmessage (note, not a direct message), I am not able to send an ios device a cloudmessage by subscribing them to a topic. 

Also I found that when I pick an audience in the cloudmessage console, targetting iOS users I don't seem to be able to pick iOS users. However when targetting Android users, all works ok!

I will see if i can find the code dealing with this in your library. 

Why is it useful to have topics, and deviceOS targeting working as expected also for FCM based messages? 
Makes my server lightweight: for example I intended to subscribe * all * users to the "app" topic. Imagine I have multiple 100'000's of users. This way i just send from my server a simple call to send a push to "topic/app" and FCM will deal with the actual calling of 100'000's FCM tokens. 

have a nice weekend!

**Comment by roelandp** [comment]
Update. tested and build some version of the module myself. I'm pretty lame at obj.c but the error being called is: 
`The subscription operation is suspended because you don't have a token. The operation will resume once you get an FCM token.
`

So somehow 'subscribeToTopic' is not aware of the fcmtoken (in it's self? environ) 

I found similar issues for example here: 
https://github.com/chemerisuk/cordova-plugin-firebase-messaging/issues/77

**Comment by roelandp** [comment]
Ok! fixed!

its all due to ordering of the loading process. 

I used to have this: 

```
var f_core = require('firebase.core');
var f_cm = require('firebase.cloudmessaging');
f_core.configure();
```
that lead to the bugs mentioned above... 

Now when changing stuff around and "configuring" the f_core prior to "requiring" the cloudmessaging module, fixes topic subscription for me!

If you agree this fixes, ill update the examples to reflect this fix. 

New: 
```
var f_core = require('firebase.core');
f_core.configure();
var f_cm = require('firebase.cloudmessaging');
```

**Comment by caspahouzer** [comment]
So we have to configure before requiring message module to get the topics working on iOS??

**Comment by roelandp** [comment]
yes. 

i hoped my remark was explanatory :)
