### ISSUE TITLE
Notifications come duplicated on devices with android 6.0

### ISSUE THREAD

**Issue by SilvioLuis** [hansemannn/titanium-firebase-cloud-messaging#66]
I am sending notifications from my php server to the firebase cloud message. On devices with android greater than 6.0 the notification arrives right, but in smaller than 6.0 arrives duplicated as in the image below.

![Screen Shot 2019-04-02 at 11 33 06](https://user-images.githubusercontent.com/6088371/55485676-4a1ecf80-5601-11e9-83e1-f19a947e2f90.png)

My Code:

```
$url = 'https://fcm.googleapis.com/fcm/send';

$fields = [
    'registration_ids' => $tokens,
    'notification' => [
        'title' => $notification['title'],
        'body' => $notification['body'],
        'sound' => 'default'
    ]/*,
    'data' => [
        'key1' => 'value1',
        'key2' => 'value2'
    ]*/
];

if ($notification['badge'] != null && $notification['badge'] !== 0) {
	$fields['notification']['badge'] = $notification['badge'];
}

$headers = [
    'Authorization: key=XXXXXXXXXX', 'Content-Type: application/json'
];
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));

$result = curl_exec($ch);
curl_close($ch);
```

When I send a message, directly through the firebase panel for android devices smaller than 6.0 the notification arrives correct .... but when I send that by my php code, on devices larger than 6.0 it arrives ONLY ONE NOTIFICATION and in less than 6.0 it arrives duplicate .

**Comment by hansemannn** [comment]
The service is only started once, so it may be something with firebase itself.
