### ISSUE TITLE
notification icon not shown

### ISSUE THREAD

**Issue by caspahouzer** [hansemannn/titanium-firebase-cloud-messaging#67]
Whatever I try, and wherever I copy the notificationicon or notification_icon, the icon on a received notification is just a grey square.

Any ideas?

**Comment by m1ga** [comment]
hi @caspahouzer were you able to solve it? Not sure what the last reply on Slack was. Otherwise we'll investigate here so it won't get lost.

**Comment by caspahouzer** [comment]
No, unfortunetaly not. Whatever I tried and wherever I put the icon in any format, the notification icon stays as a grey box

**Comment by m1ga** [comment]
Strange. This is the result:
![Screenshot_20190410-171656](https://user-images.githubusercontent.com/4334997/55891510-f8ec7e00-5bb4-11e9-9e8f-b4cb88efaa66.png)

of this image:
![Screenshot_20190410_171626](https://user-images.githubusercontent.com/4334997/55891606-220d0e80-5bb5-11e9-90e8-e70145dd038e.jpg)
(the default icon, renamed and copied to that folder)

and not sure if this is still valid: https://stackoverflow.com/a/39158869/5193915

Do you use the `notificationicon.png` version or do you set a custom path in your tiapp.xml?

**Comment by hansemannn** [comment]
We use this feature as well and don't have any issues. Make sure you have all densities and the tiapp.xml config is properly set.

**Comment by hansemannn** [comment]
<img width="354" alt="Bildschirmfoto 2019-04-23 um 07 32 43" src="https://user-images.githubusercontent.com/10667698/56557092-1a2c7180-659a-11e9-84bd-7a720eb40930.png">
+
```xml
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon"/>
```
inside your tiapp.xml `<application>` tag.
