### ISSUE TITLE
API disparity between iOS and Android

### ISSUE THREAD

**Issue by Brianggalvez** [hansemannn/titanium-firebase-cloud-messaging#7]
in iOS we have the following methods:

`- (void)subscribeToTopic:(id)topic`

`- (void)unsubscribeFromTopic:(id)topic`

while in Android: 

`public void subcribeToTopic(String topic)`

`public void unsubcribeFromTopic(String topic)`

**Comment by hansemannn** [comment]
@m1ga @Brianggalvez Can one of you submit a PR?

**Comment by m1ga** [comment]
not sure what the problem is:
https://github.com/hansemannn/titanium-firebase-cloud-messaging/blob/585823c50573917586fd79fdeefc65e771714935/ios/Classes/FirebaseCloudmessagingModule.m#L111
iOS and Android accept a string, or?
