### ISSUE TITLE
Not receiving fcm data push messages when app is in the background / closed

### ISSUE THREAD

**Issue by iQSarvesh** [hansemannn/titanium-firebase-cloud-messaging#71]
I am able to receive data messages when app is in foreground, but no luck when app is closed. Following is my code in index.js.

```javascript
var core = require('firebase.core');

	core.configure({
		file : "google-services.json"
	});
	var fcm = require('firebase.cloudmessaging');
	var androidNotification = require('/androidNotification');

	registerAndroid();
	function registerAndroid() {
		// Called when the Firebase token is registered or refreshed.
		fcm.addEventListener('didRefreshRegistrationToken', function(e) {
			Ti.API.info('Token', e.fcmToken);
			Ti.App.Properties.setString('push_token', e.fcmToken);
		});
		// Called when direct messages arrive. Note that these are different from push notifications.
		fcm.addEventListener('didReceiveMessage', function(e) {
			Ti.API.info('Message', JSON.stringify(e.message.data.message));
			androidNotification.sendNotification(e.message.data.message);
		});
		
		if (OS_ANDROID) {

			var channel = Ti.Android.NotificationManager.createNotificationChannel({
				id : 'nube_channel',
				name : 'NUBE CHANNEL',
				importance : Ti.Android.IMPORTANCE_DEFAULT,
				enableLights : true,
				enableVibration : true,
				showBadge : true
			});
			fcm.notificationChannel = channel;
		}
		
		// Register the device with the FCM service.
		fcm.registerForPushNotifications();
		// Check if token is already available.
		if (fcm.fcmToken) {
			Ti.API.info('FCM-Token', fcm.fcmToken);
			Ti.App.Properties.setString('push_token', fcm.fcmToken);
		} else {
			Ti.API.info('Token is empty. Waiting for the token callback ...');
		}
	}
```

**Comment by m1ga** [comment]
Please show the payload of the push you are sending. Android or iOS? Is the push not showing or just the data not going into the app? Does it work when you click the push and open the app with it?

**Comment by iQSarvesh** [comment]
@m1ga This issue is related to Android. I am testing it on Android 9 (API 28). Push notification is not being shown and also not getting data payload. 
Probable reason might be 'onMessageReceived' of FirebaseMessagingService class is not getting called when app is in the background. 

Below is data payload of push message -

`{
  "data": {
    "message": {
      "alert": "Your order is fullfilled by the IQ Local Ltd.",
      "type": "order_push_notification",
      "tid": ""
    }
  },
  "registration_ids": [
    "dBwLHKcJ8ZE:APA91bGqG8o-YSJXbyXj8gQagVgMO-r2r1nxkYyWKmDTVmlruIjpAS2ynloBuzM89PIKvPkqJi3FdkkCWSbUCRG4mhZKbYdoshMGoOlev404DTgHUMSdYp90pvgP6tWesxxImR9eLduK"
  ]
}`

**Comment by m1ga** [comment]
first please use three \` to format your code (check the github markdown), one is for one line code.

What do you use to send this payload? I'm not sure if the data->message->alert is correct. Normally I use it like this: https://github.com/hansemannn/titanium-firebase-cloud-messaging#android-example where data->message is the actual text it will display and not another object (or in your case alert).

Try to use the FCM console to send a test message. For me it is working correctly in fore/background when using the latest version and a simple test message from the console

**Comment by iQSarvesh** [comment]
I am using 'Postman' to test this notification request. As per firebase's official documentation, there are two types of messages -> [1. Data Message and 2. Notification message](https://firebase.google.com/docs/cloud-messaging/android/receive?authuser=2).

In my scenario, I want to receive data message only. Your above mentioned piece of PHP code is also using same data message.

As per [Firebase Documentation](https://firebase.google.com/docs/cloud-messaging/concept-options?authuser=2#notifications_and_data_messages), we can use custom payload under "data" key. So here, "message" is my custom payload. It is also working in the foreground.

I also have tried sending push notifications using console, but getting same result as postman.

**Comment by m1ga** [comment]
just saying, that it won't produce any notification since you are not using a title/message. 
The module will use `message` as the text for the data message: https://github.com/hansemannn/titanium-firebase-cloud-messaging/blob/master/android/src/firebase/cloudmessaging/TiFirebaseMessagingService.java#L180 and you are sending an object, not a text.

**Comment by iQSarvesh** [comment]
Ok thanks! I will try this solution and let you know. I am very thankful for your prompt help.

**Comment by hansemannn** [comment]
Please use StackOverflow or TiSlack for questions, thanks!
