### ISSUE TITLE
Notification icon shown in notification message, but not in data message

### ISSUE THREAD

**Issue by danny005** [hansemannn/titanium-firebase-cloud-messaging#72]
I think this issue isn't resolved:

https://github.com/hansemannn/titanium-firebase-cloud-messaging/issues/67

Sending notification message works fine. But in a data mesage, the default notification icon is not shown. And yes, I have updated the tiapp.xml as suggested, otherwise the notification message wouldn't display the icon.

**Comment by m1ga** [comment]
I'll test it again at the weekend. Do you have a sample project (without the firebase JSON) which doesn't work for you so I can run that?

**Comment by danny005** [comment]
I have tested it in a very large project, so no sample project available, sorry. But can provide a sample project with Ti Classic if required.

**Comment by m1ga** [comment]
that would be very helpful so I check the icons and places

**Comment by m1ga** [comment]
With a data notification I'll get the `app/platform/android/res/drawable/notificationicon.png` icon
![Screenshot_20190428-182600](https://user-images.githubusercontent.com/4334997/56867223-448b8e00-69e3-11e9-95d6-676a5672b049.png)
appicon is a 2, notificationicon is a 1 (as shown in the status bar) without any changes in tiapp.xml.

**Comment by danny005** [comment]
Hmm, should it be notification_icon.png or notificationicon.png (without underscore)? Can you upload it as demo project to Github? Will give it a try.

**Comment by m1ga** [comment]
depends: https://github.com/hansemannn/titanium-firebase-cloud-messaging#setting-the-notification-icon

without any changes to the tiapp.xml you have to use the "without underscore" variant. If you set a custom icon you just name it like you want to e.g. `@drawable/notificationicon` or `@drawable/notification_icon` and the png file according to it.
Without the tiapp.xml line you will get the default icon for `notification messages`. A `data message` uses the `notificationicon.png`

**Comment by m1ga** [comment]
[test_fcm.zip](http://migaweb.de/test_fcm.zip)
I hope this still works :smile:  I've copied the code parts to new clean project and hope everything is included besides the google-services.json (place that in the assets/android folder)
