### ISSUE TITLE
foreground notifications not calling didReceiveMessage when clicked

### ISSUE THREAD

**Issue by ricardoroth** [hansemannn/titanium-firebase-cloud-messaging#77]
Notifications received when in background, open the app and trigger  didReceiveMessage, but it looks like the ones received in foreground only open the app, but do not trigger the event.

It would be ideal to have the same behavior in both cases.

**Comment by m1ga** [comment]
What kind of message are you sending?
Using a normal data message with show in foreground I'll receive a notification and the didReceiveMessage is triggered right away when the message arrives since you have it open already.
If I click the notification I receive the message in the lastData

**Comment by ricardoroth** [comment]
The scenario would be:
- app is open
- notification received
- put the app in background (for whatever reason)
- tap on the notification

The expected behavior would be the same as if the notification had been received while the app was in the background.

I will close this issue because the description is not so accurate, and create a new one when I find out exactly what's going on.
