### ISSUE TITLE
Registration to push notification issue

### ISSUE THREAD

**Issue by ma7moudAziz** [hansemannn/titanium-firebase-cloud-messaging#81]
When I try to register to push notification on android it returns the following error "FirebaseInstanceId: Token retrieval failed: INVALID_SENDER".

This issue appears just after Google released the FCM version 18.0.0 it seems that there is some changes need to be done.

Best Regards.

**Comment by hansemannn** [comment]
Please check your setup and ask the TiSlack community for help regarding questions. This repo should only contain reports about module bugs, which this isn't.

**Comment by ma7moudAziz** [comment]
Hi @hansemannn,
My setup was correct as I mentioned it was working just fine last week it kept working on ios but on Android, it stops working due to some changes made by Google. 
Here is my setup: 
`var fcm = require('firebase.cloudmessaging'),
        core = require('firebase.core');

if (fcm.lastData && !_.isEmpty(fcm.lastData) && fcm.lastData.data) {
           do some stuff
        }

fcm.addEventListener('didReceiveMessage', addBadgeNumber);

        var channel = Ti.Android.NotificationManager.createNotificationChannel({
            id: 'xxx',
            name: Ti.App.name,
            importance: Ti.Android.IMPORTANCE_DEFAULT,
            enableLights: true,
            enableVibration: true,
            showBadge: true
        });

        fcm.notificationChannel = channel;

        fcm.registerForPushNotifications();

        if (fcm.fcmToken) {
            console.log("tokennsss fcm.fcmToken");
            console.log(fcm.fcmToken);
        }

        fcm.addEventListener('didRefreshRegistrationToken', function (e) {
            console.log("tokennsss e.fcmToken");
            console.log(e.fcmToken);
        });
`
And offcourse i've added the google-services.json file where is suppose to be and everything as i mentioned before was working just fine last week.

**Comment by m1ga** [comment]
@ma7moudAziz please use the XML version https://github.com/hansemannn/titanium-firebase#android-notes
and the module is not using `18.0.0`. The current version is using `16.1.2` (make sure to include that ti.playservice version if you are using the latest Ti SDK).
And make sure to require FCM after the core.

INVALID_SENDER is refering to a element in the config. So that might be disabled or changed. So check the firebase console

**Comment by ma7moudAziz** [comment]
Hi @m1ga thanks very much for your help adding the XML version as you mentioned just do the trick.
