### ISSUE TITLE
Error: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.iid.FirebaseInstanceId.getInstanceId()' on a null object reference

### ISSUE THREAD

**Issue by antonioduran** [hansemannn/titanium-firebase-cloud-messaging#82]
Hello. Good afternoon / evening.

I am getting the following issue when I try to use the following combinations of the modules:
`Error: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.iid.FirebaseInstanceId.getInstanceId()' on a null object reference`

This issue happen when the module of Firebase.cloudmessaging is trying to execute this method: **registerForPushNotifications**

```
<module version="16.1.3">ti.playservices</module>
<module version="5.0.0">firebase.core</module>
<module version="3.0.0">firebase.analytics</module>
<module version="2.0.1">firebase.cloudmessaging</module>
```

I have been trying a lot of combinations with the versions of the modules without success. 

but, if I remove this module (<module version="3.0.0">firebase.analytics</module>) the other modules will work pretty good.

More info:
8.0.2.GA Ti SDK.
Alloy version: 1.13.10
Node version: v8.9.1
Appcelerator CLI : 7.0.11 

Also I found that other guy has the same situation in the following thread:
 fahad86 on Mar 26 Contributor

Getting this error while invoking registerPush:

```
Error: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.iid.FirebaseInstanceId.getInstanceId()' on a null object reference
    at Object.exports.registerPushNotification (/push_notification.js:354:19)
    at onInitialWindowOpen (/alloy/controllers/index.js:351:32)
    at Drawer.onDrawFirstOpen (/alloy/controllers/index.js:456:1150)
    at Drawer.value (ti:/events.js:49:21)
    at Drawer.value (ti:/event
```
Reference:
https://github.com/hansemannn/titanium-firebase-cloud-messaging/pull/51

Thanks, and best,
Antonio.

**Comment by m1ga** [comment]
Do you use the `strings.xml` to set your ID? And where do you do your `fc.configure()` part?

**Comment by antonioduran** [comment]
Hello @m1ga . Good afternoon / evening.

Yes I use strings.xml to se the google_app_id, and it is working pretty good whether I use just the following modules:
```
<module version="16.1.3">ti.playservices</module>
<module version="5.0.0">firebase.core</module>
<module version="2.0.1">firebase.cloudmessaging</module>
```
and the fc.configure() I have it in the index.js before doing any operation with the other modules mentioned before.

The issue is just when I try to integrate the firebase.analytics with the other modules.

Thanks, and best,
Antonio.

**Comment by antonioduran** [comment]
Hello @m1ga . I solved the issue, doing a research I found a post, and I added the suggestion from that post, and now, all modules are working good .

```
 <service android:name="com.google.firebase.components.ComponentDiscoveryService" >
            <meta-data
                android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
                android:value="com.google.firebase.components.ComponentRegistrar" />
 </service>
```

Thanks, and best,
Antonio.

**Comment by m1ga** [comment]
Interesting, thanks! I'll add this to the README! Then I'll close this ticket

**Comment by malhajj** [comment]
Hi There,
Hope you're still supporting this module,
We are still facing this issue in our case, even after adding the suggested solution in Tiapp.xml.
There is fired just after using "fcm.registerForPushNotifications();"
Any help would be appreciated

**Comment by m1ga** [comment]
@malhajj sure, last update was two days ago ;-)

Can you give more some information, please. e.g. your included modules and which version. And I think it would be good to create a new issue

**Comment by malhajj** [comment]
Thanks @m1ga for the update,
I removed fcm.registerForPushNotifications(); and the last version works fine
