### ISSUE TITLE
Android - Push notification - empty intent

### ISSUE THREAD

**Issue by luisestudioalfa** [hansemannn/titanium-firebase-cloud-messaging#84]
Hello,

I'm using the module and i subscribe to the notifications. When the app is open the method "didReceiveMessage" works as planned and the data of the notification is shown.

But when the app is on background the push notification is received and when i click on it i can't get the data. I'm using a Google pixel 3 XL with Android 9.0.

I have also tested it on a Samsung Galaxy S6 with android 6 with the same result...

[INFO] :   data null
[INFO] :   data data null
[INFO] :   fcm_data null
[INFO] :   last data - {}
[INFO] :   last fcm - {}
[INFO] :   No data

I'm using the versions:
Firebase.core - 5.0.0
Firebase.cloudmessaging - 2.0.1

In the index.js i have the following code to check the intent:

```
function checkIntent() {
		var act = Titanium.Android.currentActivity;
		var _intent = act.intent;
		console.log("data", _intent.getData());
		console.log("data data", _intent.getStringExtra("data"));
		console.log("fcm_data", _intent.getStringExtra("fcm_data"));
		
		console.log(Alloy.Globals.fcm.lastData);
		
		Ti.API.info('last data - '+JSON.stringify(Alloy.Globals.fcm.lastData));
		
		Ti.API.info('last fcm - '+JSON.stringify(Alloy.Globals.fcm));
		
		if (Object.keys(Alloy.Globals.fcm.lastData).length === 0) {
		  // No data
		  Ti.API.info('No data');
		}
		else
		{
			Ti.API.info('Data - YES');
		}
	}
```

Any ideas of what i'm doing wrong?

Thank you in advance!.

**Comment by m1ga** [comment]
Did you also check your `didReceiveMessage` event?

Following scenario is working for me:

**app in background (so still visible in task switcher):**
* data notification arrives
* clicking the notification -> app comes to foreground
* data is shown here:
```
function checkIntent() {
	var act = Titanium.Android.currentActivity;
	var _intent = act.intent;
	console.log("fcm_data", _intent.getStringExtra("fcm_data"));
	console.log(fcm.lastData);
}
```

**app is closed (not visible in task switcher)**
* data notification arrives
* clicking the notification -> app is opening
* `didReceiveMessage` is called with the data

This is my test controller:
```
var fc = require('firebase.core');
var fcm = require('firebase.cloudmessaging');

fc.configure();

fcm.createNotificationChannel({
	sound: 'notification',
	channelId: 'default',
	channelName: 'General Notifications',
	importance: 'high',
	vibrate: true,
	sound: true,
	lights: true,
	showBadge: true
});

fcm.addEventListener("didRefreshRegistrationToken", onToken);
fcm.addEventListener("didReceiveMessage", onMessage);
fcm.registerForPushNotifications();

function onToken(e) {}

function onMessage(e) {
	console.log("Got message: " + (e.message.data));
	console.log("Got message: " + JSON.stringify(e.message));
}

function checkIntent() {
	var act = Titanium.Android.currentActivity;
	var _intent = act.intent;
	console.log("fcm_data", _intent.getStringExtra("fcm_data"));
	console.log(fcm.lastData);
}

$.index.addEventListener("open", function() {
	checkIntent()
	if (this.activity) {
		this.activity.onResume = function() {
			checkIntent()
		};
	} else {
		Ti.App.addEventListener("resumed", function() {
			checkIntent()
		});
	}
});

$.index.open();
```

**Comment by luisestudioalfa** [comment]
Hello M1ga,

Thank you for answering, my controller looks identical to yours, but the function `didReceiveMessage ` is not been called when the app is in background or the app is closed, is only called when the app is open in foreground.

My index.js controller has most of the lines of your controller. I have more lines in the function `checkIntent` to call to actions and so, but the rest is the same.

I have changed the channelId value and the channelName value. I think it's something like this:

```
fcm.createNotificationChannel({
	channelId: 'randomname',
	channelName: 'randomname2',
        importance: Ti.Android.IMPORTANCE_DEFAULT,
        enableLights: true,
        enableVibration: true,
        showBadge: true
});
```

But not working in those cases..... I will try again on monday.

Thank you for your time.

**Comment by luisestudioalfa** [comment]
Hello m1ga,

I have tested today, copying your example but without success...

This is my index.js
```

	Alloy.Globals.core = require('firebase.core');
	Alloy.Globals.core.configure({
	 	file : "google-services.json"
	});
	Alloy.Globals.fcm = require('firebase.cloudmessaging');
	
	Alloy.Globals.fcm.createNotificationChannel({
		channelId: 'broadcast',
		channelName: 'broadcast',
		importance: Ti.Android.IMPORTANCE_DEFAULT,
		enableLights: true,
		enableVibration: true,
		showBadge: true
	});
	
	Alloy.Globals.fcm.addEventListener("didRefreshRegistrationToken", onToken);
	Alloy.Globals.fcm.addEventListener("didReceiveMessage", onMessage);
	Alloy.Globals.fcm.registerForPushNotifications();
	
	function onToken(e) {
		Ti.API.info('Token 1', e.fcmToken);
		Ti.App.Properties.setString('push_token', e.fcmToken);
	}
	
	function onMessage(e) {
		var jsdata = JSON.parse(e.message.data.data);
		Ti.API.info('jsdata - ', jsdata);
	  	Alloy.Globals.showmessage(jsdata);
	}

	$.index.addEventListener('open', function(){
	    // Grab the window's action bar instance and call the hide method
		$.index.activity.actionBar.hide();
		
		checkIntent();
		if (this.activity) {
			this.activity.onResume = function() {
				checkIntent();
			};
		} else {
			Ti.App.addEventListener("resumed", function() {
				checkIntent();
			});
		}
	});

	 if (Alloy.Globals.fcm.fcmToken) {
		  Ti.API.info('FCM-Token 2', Alloy.Globals.fcm.fcmToken);
		  Ti.App.Properties.setString('push_token', Alloy.Globals.fcm.fcmToken);
	 } else {
	  	Ti.API.info('Token is empty. Waiting for the token callback ...');
	 }
	
	function checkIntent() {
		var act = Titanium.Android.currentActivity;
		var _intent = act.intent;
		console.log("data", _intent.getData());
		console.log("data data", _intent.getStringExtra("data"));
		console.log("fcm_data", _intent.getStringExtra("fcm_data"));
		
		console.log(Alloy.Globals.fcm.lastData);
		
		Ti.API.info('last data - '+JSON.stringify(Alloy.Globals.fcm.lastData));
		
		Ti.API.info('last fcm - '+JSON.stringify(Alloy.Globals.fcm));
		
		if (Object.keys(Alloy.Globals.fcm.lastData).length === 0) {
		  // No data
		  Ti.API.info('No data');
		}
		else
		{
			Ti.API.info('Data - YES');
		}
	}

	//After the user has logged in, in the app i create some custom channel for each user
	function registerAndroidPush(channel) {

	user_device_token = Ti.App.Properties.getString('push_token');
 
	for(var i=0;i<channel.length;i++)
	{
		var topic = channel[i].replace("/", "_");
		Ti.API.info('topic - '+topic);
		Alloy.Globals.fcm.subscribeToTopic(topic);
	}
}
```

I'm not sure of what i'm doing wrong for it not to work...

Thank you in advance!

**Comment by m1ga** [comment]
what kind of notification are you sending? Notification, data or mixed?

**Comment by luisestudioalfa** [comment]
Thank you m1ga.

After lots of tries and tests, i have updated the code and now i receive the notifications, but when i tried to publish the app, google play console rejected the app because i was using the `android:targetSdkVersion="25"` and i have to update it to at least `android:targetSdkVersion="26"` 

So, back to the code, i updated the android target SDK version to 26, and now when i test the notifications, they work with the app open, but on the app closed the message that shows is:

`"Developer warning for package "XXX.XXX.XXX" Failed to post notification on channel "null".`

In my code i have:

```
fcm.createNotificationChannel({
		sound: 'notification',
		channelId: 'default',
		channelName: 'General Notifications',
		importance: 'high',
		vibrate: true,
		sound: true,
		lights: true,
		showBadge: true
	});
```

So not sure, what i would need... Do i have to add anything to the tiapp.xml?

Thank you in advance.

**Comment by luisestudioalfa** [comment]
I think i found the problem with my null channelid. 

In my app the channel is defined and when i send notifications from firebase they reach the device. But i have a parse server in which the devices register, and when i send a notification from my parse, they reach the device if the app is in foreground, but the notification is not shown if the app is in background...

So i think that the communication between the parse and the firebase lacks some field or something, but i'm unable to find the needed field...

Thank you for your help m1ga!
