### ISSUE TITLE
Any callback method to get data when app is closed?

### ISSUE THREAD

**Issue by Hemantsolanki103** [hansemannn/titanium-firebase-cloud-messaging#85]
Hi All,

Any callback method to get data when app is closed and user click on notification tray?
I saw some intent related solution but its not proper way.

Could you please add callback for the above? I would really help for all the developers.

Thanks & Regards,
Hemant Solanki

**Comment by hansemannn** [comment]
You can get the data from the boot intent when launching the app.

**Comment by hansemannn** [comment]
Please check with the community if you have further questions, as this is not Firebase related.
