### ISSUE TITLE
While app in background, once notification clicked, it always restart the app

### ISSUE THREAD

**Issue by dyan02** [hansemannn/titanium-firebase-cloud-messaging#86]
thanks for the library, i have 1 issue, when app is in the background (not closed), and push notification arrives, then i click on the Push Notification, instead of resuming the activity, it restart the application.

im using TISDK 8.1.0, Firebase cloud messaging 2.0.1

**Comment by m1ga** [comment]
please have a look at this thread https://ti-slack.slack.com/archives/C03CVQX2A/p1565986910101200 at TiSlack.

**Comment by tomjakobs1** [comment]
Looking for an answer for this aswell. I havent got access to the workspace. Could you post it here?

**Comment by nuborian** [comment]
Same problem here ... Still not working for me
