### ISSUE TITLE
FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE

### ISSUE THREAD

**Issue by roelandp** [hansemannn/titanium-firebase-cloud-messaging#89]
Android 7 / Android 7.1 only

- using Ti.Playservices 16.3 / 16.4 
- latest FB_core
- latest FB_ana
- latest FB_cloudmessaging

Whatever I try only on android 7/7.1 I get these dreaded: 
`FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE`

Happening on Genymotions and Android 7's in the wild. Basically the app won't launch. 

Any suggestions for workarounds, solutions, would be very welcome.

**Comment by roelandp** [comment]
with help of @m1ga we managed to replace my files with his and it started working... Only thing i noticed differently with miga's setup and mine was: 

requiring all 3 modules (fcore, fana, fcloud) prior to calling fcore.config() 

Still don't understand why that would be of influence (and only on Android7)

**Comment by Taneeyo** [comment]
try to AVD---cold play ！Do not use quick play
