### ISSUE TITLE
didReceiveMessage listener not working

### ISSUE THREAD

**Issue by ManasMack** [hansemannn/titanium-firebase-cloud-messaging#9]
**didReceiveMessage** listener not getting fired after receiving the push notification.
When app is running not getting notification only receiving the notification when app is in background.

Titanium SDK: 7.1.0. GA
firebase.cloudmessaging : 1.1.0
firebase.core : 1.1.0
Device : iPhone 5S - iOS 11.3

Please share demo code for reference

**Comment by hansemannn** [comment]
Hey there! Please refer to the readme: 

> iOS Note: This method is only called on iOS 10+ and only for direct messages sent by Firebase. Normal Firebase push notifications are still delivered via the Titanium notification events, e.g. notification and remotenotification.

**Comment by ManasMack** [comment]
Titanium notification events, e.g. notification and remotenotification.

Can you please share a example to use them

**Comment by hansemannn** [comment]
Please follow the general push notifications guide to setup push notifications and it‘s event listeners.
