### ISSUE TITLE
No notification sound when app is in foreground

### ISSUE THREAD

**Issue by Wingee** [hansemannn/titanium-firebase-cloud-messaging#95]
When the app is in the background and an FCM message comes in the default notification sound plays. When the app is in the foreground no notification sound plays.

**Comment by m1ga** [comment]
Which platform and did you create a custom local notification for that?

**Comment by Wingee** [comment]
I've tried it on both iOS and Android. No I didn't create a local notification for it - I use the didReceiveMessage event when a push notification comes in.

**Comment by m1ga** [comment]
when you app is in foreground it won't trigger a notification, so you have to do that yourself

**Comment by Wingee** [comment]
ok thanks
