### ISSUE TITLE
no way of knowing when push notification tapped by user

### ISSUE THREAD

**Issue by upngo** [hansemannn/titanium-firebase-cloud-messaging#97]
ANDROID

say i receive two push notifications while the app is in the background. 
i tap one and it opens the app firing the resume event, and i can check the lastData to find info about which notification was tapped.
if i tap the other notification in the tray then it will update lastData however there's no event triggered to tell me that i should do anything. the app is unawares.

the ideal solution would be to trigger an event whenever a notification is tapped because then i could handle everything (foreground, background, closed) push notifications the same

**Comment by mitulbhalia** [comment]
Same issue at my side too.  I also want to trigger notification click event.
IS there any solution?

**Comment by m1ga** [comment]
Did you try to read the intent data in the open event like this?

```
$.index.addEventListener("open", function() {
	var act = Titanium.Android.currentActivity;
	var _intent = act.intent;
	var message = _intent.getStringExtra("fcm_data");
	console.log("FCM",message);
});
```

* I send two FCM push messages
* Click the first one to open the app
* get the data from the clicked intent
* drag down the drawer and click the second one
* get the data from the second clicked intent

**Comment by mitulbhalia** [comment]
@m1ga Actually I am testing it in classic version so please tell me where to test this code?
in app.js or on window's open event?

**Comment by macasfaj** [comment]
> @m1ga Actually I am testing it in classic version so please tell me where to test this code?
> in app.js or on window's open event?

Windows open event is fine ;)

**Comment by qasim90** [comment]
Here's one example of handling notification clicking for both app launch and resume cases:
~~~
        const handleNotificationClick = (notifObj) => {
		if(notifObj) {
			notifData = JSON.parse(notifObj);
			// Prcoess notification data however you like

			fcm.clearLastData();
		}
	}
        // Check if app was launched on notification click
	const launchIntent = Ti.Android.rootActivity.intent;
	handleNotificationClick(launchIntent.getStringExtra("fcm_data"));

        // App was resumed from bacground on notification click
	Ti.App.addEventListener('resumed',function(){
		const currIntent = Titanium.Android.currentActivity.intent;
		var notifData = currIntent.getStringExtra("fcm_data");
		//console.log('resume fcm_data:', notifData);

		handleNotificationClick(notifData);
	});
~~~
Would be good if something like this is included in Readme example as this may not be very straight forward for many people like me :)
